#include "defines.h"
#include "../include/follower_mon.h"
#include "../include/follower_mon_sprites.h"
#include "../include/pokemon.h"
#include "../include/new/follow_me.h"
#include "../include/global.fieldmap.h"
#include "../include/event_object_movement.h"
#include "../include/script_menu.h"
#include "../include/new_menu_helpers.h"
#include "../include/script.h"
#include "../include/follower_mon_pal.h"
#include "../include/new/character_customization.h"


extern u8 SparkleTiles[];
extern u16 SparklePal[];

static void SpriteCB_Sparkle(struct Sprite *sprite);

static const struct OamData sSparkleOamData =
{
    .y = 0,
    .affineMode = ST_OAM_AFFINE_NORMAL,
    .objMode = ST_OAM_OBJ_NORMAL,
    .mosaic = 0,
    .bpp = ST_OAM_4BPP,
    .shape = ST_OAM_SQUARE,
    .x = 0,
    .matrixNum = 0,
    .size = ST_OAM_SIZE_2,
    .tileNum = 0,
    .priority = 0,
    .paletteNum = 0,
    .affineParam = 0,
};

static const union AnimCmd sSparkleAnim0[] =
{
    ANIMCMD_FRAME(0, 5),
    ANIMCMD_FRAME(16, 5),
    ANIMCMD_FRAME(32, 5),
    ANIMCMD_FRAME(48, 5),
    ANIMCMD_FRAME(64, 5),
    ANIMCMD_FRAME(80, 5),
    ANIMCMD_END,
};

static const union AffineAnimCmd sSparkleAffineAnim0[] =
{
    AFFINEANIMCMD_FRAME(256, 256, 0, 0),
    AFFINEANIMCMD_FRAME(4, 4, 8, 30),
    AFFINEANIMCMD_END,
};

static const union AnimCmd *const sSparkleAnimTable[] =
{
    sSparkleAnim0,
};

static const union AffineAnimCmd *const sSparkleAffineAnimTable[] =
{
    sSparkleAffineAnim0,
};

static struct SpriteSheet sSparkleTileData =
{
    .data = SparkleTiles,
    .size = (192 * 32) / 2,
    .tag = 12,
};

static struct SpritePalette sSparklePalData =
{
    .data = SparklePal,
    .tag = 12,
};

static struct SpriteTemplate sSparkleTemplate =
{
    .tileTag = 12,
    .paletteTag = 12,
    .oam = &sSparkleOamData,
    .anims = sSparkleAnimTable,
    .images = NULL,
    .affineAnims = sSparkleAffineAnimTable,
    .callback = SpriteCB_Sparkle,
};

static void SpriteCB_Sparkle(struct Sprite *sprite)
{
    if (sprite->data[0] == 30)
        DestroySprite(sprite);
    else
        sprite->data[0]++;
}

void CreateSparkleSprite(void)
{
    if (FlagGet(FLAG_FOLLOWER_POKEMON) && gFollowerState.inProgress)
    {
        struct Sprite *followerSprite = &gSprites[gEventObjects[gFollowerState.objId].spriteId];
        s16 posX = followerSprite->pos1.x - 16;
        s16 posY = followerSprite->pos1.y - 10;
        u8 spriteId;

        LoadSpriteSheet(&sSparkleTileData);
        LoadSpritePalette(&sSparklePalData);
        spriteId = CreateSprite(&sSparkleTemplate, posX, posY, 0);

        gSprites[spriteId].data[0] = 0;
        gSprites[spriteId].centerToCornerVecX = 0;
        gSprites[spriteId].centerToCornerVecY = 0;
        gSprites[spriteId].coordOffsetEnabled = TRUE;
    }
}

u16 GetFollowerMonSprite(void)
{
    u8 slotId = 7;
    u16 species;

    for (u8 i = 0; i < gPlayerPartyCount; ++i)
    {
        if (!GetMonData(&gPlayerParty[i], MON_DATA_IS_EGG, NULL)
         && GetMonData(&gPlayerParty[i], MON_DATA_HP, NULL) > 0)
        {
            slotId = i;
            break;
        }
    }

    if (slotId == 7)
        return 0;

    struct Pokemon* mon = &gPlayerParty[slotId];
    species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    return gFollowerMonSpriteIdTable[species] + 256;
}

void CreateFollowerMonObject(void)
{
    u16 sprite = GetFollowerMonSprite();
    if (sprite == 0)  // If there is no valid Pokémon, do not create the follower
        return;
    struct EventObject *playerObj = &gEventObjects[gPlayerAvatar->eventObjectId];
 
         s16 posX = playerObj->currentCoords.x - 7;
         s16 posY = playerObj->currentCoords.y - 7;
     
         // Adjusts follower position based on player direction
         switch (playerObj->facingDirection)
    {
        case DIR_SOUTH: posY -= 1; break;
         case DIR_NORTH: posY += 1; break;
         case DIR_WEST:  posX += 1; break;
         case DIR_EAST:  posX -= 1; break;
     }
 
     // Check if follower already exists before creating a new one
     for (u8 i = 0; i < MAP_OBJECTS_COUNT; i++)
     {
         if (gEventObjects[i].localId == 30 && gEventObjects[i].active)
             return;  // There is already a follower, so don't create another one
    }

    struct EventObjectTemplate followerObj =
    {
        .localId = 30,
        .graphicsIdLowerByte = sprite & 0xFF,
        .graphicsIdUpperByte = sprite >> 8,
        .x = posX,
        .y = posY,
        .elevation = 3,
        .movementType = 1,
        .movementRangeX = 0,
        .movementRangeY = 0,
        .trainerType = 0,
        .trainerRange_berryTreeId = 0,
    };

    SpawnSpecialEventObject(&followerObj);
}

void FollowerMonFacePlayer(void)
{
    u8 dir;

    switch (gEventObjects[gPlayerAvatar->eventObjectId].facingDirection)
    {
        case DIR_SOUTH:
            dir = DIR_NORTH;
            break;
        case DIR_NORTH:
            dir = DIR_SOUTH;
            break;
        case DIR_WEST:
            dir = DIR_EAST;
            break;
        case DIR_EAST:
            dir = DIR_WEST;
            break;
        case DIR_SOUTHWEST:
            dir = DIR_SOUTHEAST;
            break;
        case DIR_SOUTHEAST:
            dir = DIR_SOUTHWEST;
            break;
        case DIR_NORTHWEST:
            dir = DIR_NORTHEAST;
            break;
        case DIR_NORTHEAST:
            dir = DIR_NORTHWEST;
            break;
        default:
            dir = DIR_NORTH;
            break;
    }

    EventObjectTurn(&gEventObjects[gFollowerState.objId], dir);
}

void TurnFollowerMonToPlayer(void)
{
    u8 dir = gEventObjects[gPlayerAvatar->eventObjectId].facingDirection;
    EventObjectTurn(&gEventObjects[gFollowerState.objId], dir);
}

void ShowFollowerMon(void)
{
    if (FlagGet(FLAG_FOLLOWER_POKEMON) && gFollowerState.inProgress)
        gEventObjects[gFollowerState.objId].invisible = FALSE;
}
extern void Task_ScriptShowMonPic(u8 taskId);
#define gMonPaletteTable (*((struct CompressedSpritePalette**) 0x8000130))
#define gMonShinyPaletteTable (*((struct CompressedSpritePalette**) 0x8000134))

struct CompressedSpritePalette * GetSpritePalToUse(bool8 isShiny)
{
    if(isShiny)
        return gMonShinyPaletteTable;
    else
        return gMonPaletteTable;
}

u8 CreateMonSprite_MysteryGift(u16 species, s16 x, s16 y)
{
    struct Pokemon* mon = &gPlayerParty[0];
    u32 personality = 0xFFFFFFFF;
    u32 otId = T1_READ_32(gSaveBlock2->playerTrainerId);
    u16 isShiny = IsMonShiny(mon);
    const struct CompressedSpritePalette * spritePal = GetSpritePalToUse(isShiny);
    u16 spriteId = CreateMonPicSprite_HandleDeoxys(species, otId, personality, 1, x, y, 0, spritePal[species].tag);
    LoadCompressedSpritePalette(&spritePal[species]);
    if(spriteId != 0xFFFF)
    {
        gSprites[spriteId].oam.paletteNum = IndexOfSpritePaletteTag(spritePal[species].tag);
    }
    if (spriteId == 0xFFFF)
        return MAX_SPRITES;
    else
        return spriteId;
}

bool8 ScriptMenu_ShowMysteryPokemonPic(u16 species, u8 x, u8 y)
{
    u8 spriteId;
    u8 taskId;
    if (FindTaskIdByFunc(Task_ScriptShowMonPic) != 0xFF)
        return FALSE;
    spriteId = CreateMonSprite_MysteryGift(species, 8 * x + 40, 8 * y + 40);
    taskId = CreateTask(Task_ScriptShowMonPic, 80);
    gTasks[taskId].data[0] = 0;
    gTasks[taskId].data[1] = species;
    gTasks[taskId].data[2] = spriteId;
    gSprites[spriteId].callback = SpriteCallbackDummy;
    gSprites[spriteId].oam.priority = 0;
    SetStandardWindowBorderStyle(gTasks[taskId].data[5], TRUE);
    ScheduleBgCopyTilemapToVram(0);
    return TRUE;
}

bool8 ShowMysteryGiftMon()
{
    u16 species = VarGet(0x4004);
    u8 x = 0x1A;
    u8 y = 0x2;

    ScriptMenu_ShowMysteryPokemonPic(species, x, y);
    return FALSE;
}
#define tState        data[0]
#define tSpecies      data[1]
#define tSpriteId     data[2]
#define tWindowId     data[5]
void Remove_PokemonPic(void)
{
    u8 taskId = FindTaskIdByFunc(Task_ScriptShowMonPic);
    
    if (taskId != 0xFF)
    {
        u8 spriteId = gTasks[taskId].tSpriteId;

        if (spriteId < MAX_SPRITES)
        {
            struct Sprite *sprite = &gSprites[spriteId];

            FreeSpriteOamMatrix(sprite);
            DestroySprite(sprite);
            FreeSpriteTiles(sprite);
            FreeSpritePalette(sprite);
        }
        DestroyTask(taskId);
    }
}
struct Pokemon* GetFirstValidPartyMon(void)
{
    for (int i = 0; i < PARTY_SIZE; i++)
    {
        struct Pokemon* mon = &gPlayerParty[i];

        if (GetMonData(mon, MON_DATA_SPECIES, NULL) != SPECIES_NONE
            && !GetMonData(mon, MON_DATA_IS_EGG, NULL)
            && GetMonData(mon, MON_DATA_HP, NULL) > 0)
        {
            return mon;
        }
    }
    return NULL;
}

static u8 GetFollowerMapObjId(void)
{
	return gFollowerState.objId;
}

static const u16 sSpeciesToPaletteTag[] =
{
    [SPECIES_BULBASAUR] = OBJ_EVENT_PAL_TAG_BULBASAUR_SHINY,
    [SPECIES_IVYSAUR] = OBJ_EVENT_PAL_TAG_IVYSAUR_SHINY,
    [SPECIES_VENUSAUR] = OBJ_EVENT_PAL_TAG_VENUSAUR_SHINY,
    [SPECIES_CHARMANDER] = OBJ_EVENT_PAL_TAG_CHARMANDER_SHINY,
    [SPECIES_CHARMELEON] = OBJ_EVENT_PAL_TAG_CHARMELEON_SHINY,
    [SPECIES_CHARIZARD] = OBJ_EVENT_PAL_TAG_CHARIZARD_SHINY,
    [SPECIES_SQUIRTLE] = OBJ_EVENT_PAL_TAG_SQUIRTLE_SHINY,
    [SPECIES_WARTORTLE] = OBJ_EVENT_PAL_TAG_WARTORTLE_SHINY,
    [SPECIES_BLASTOISE] = OBJ_EVENT_PAL_TAG_BLASTOISE_SHINY,
    [SPECIES_CATERPIE] = OBJ_EVENT_PAL_TAG_CATERPIE_SHINY,
    [SPECIES_METAPOD] = OBJ_EVENT_PAL_TAG_METAPOD_SHINY,
    [SPECIES_BUTTERFREE] = OBJ_EVENT_PAL_TAG_BUTTERFREE_SHINY,
    [SPECIES_WEEDLE] = OBJ_EVENT_PAL_TAG_WEEDLE_SHINY,
    [SPECIES_KAKUNA] = OBJ_EVENT_PAL_TAG_KAKUNA_SHINY,
    [SPECIES_BEEDRILL] = OBJ_EVENT_PAL_TAG_BEEDRILL_SHINY,
    [SPECIES_PIDGEY] = OBJ_EVENT_PAL_TAG_PIDGEY_SHINY,
    [SPECIES_PIDGEOTTO] = OBJ_EVENT_PAL_TAG_PIDGEOTTO_SHINY,
    [SPECIES_PIDGEOT] = OBJ_EVENT_PAL_TAG_PIDGEOT_SHINY,
    [SPECIES_RATTATA] = OBJ_EVENT_PAL_TAG_RATTATA_SHINY,
    [SPECIES_RATICATE] = OBJ_EVENT_PAL_TAG_RATICATE_SHINY,
    [SPECIES_SPEAROW] = OBJ_EVENT_PAL_TAG_SPEAROW_SHINY,
    [SPECIES_FEAROW] = OBJ_EVENT_PAL_TAG_FEAROW_SHINY,
    [SPECIES_EKANS] = OBJ_EVENT_PAL_TAG_EKANS_SHINY,
    [SPECIES_ARBOK] = OBJ_EVENT_PAL_TAG_ARBOK_SHINY,
    [SPECIES_PIKACHU] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_RAICHU] = OBJ_EVENT_PAL_TAG_RAICHU_SHINY,
    [SPECIES_SANDSHREW] = OBJ_EVENT_PAL_TAG_SANDSHREW_SHINY,
    [SPECIES_SANDSLASH] = OBJ_EVENT_PAL_TAG_SANDSLASH_SHINY,
    [SPECIES_NIDORAN_F] = OBJ_EVENT_PAL_TAG_NIDORAN_F_SHINY,
    [SPECIES_NIDORINA] = OBJ_EVENT_PAL_TAG_NIDORINA_SHINY,
    [SPECIES_NIDOQUEEN] = OBJ_EVENT_PAL_TAG_NIDOQUEEN_SHINY,
    [SPECIES_NIDORAN_M] = OBJ_EVENT_PAL_TAG_NIDORAN_M_SHINY,
    [SPECIES_NIDORINO] = OBJ_EVENT_PAL_TAG_NIDORINO_SHINY,
    [SPECIES_NIDOKING] = OBJ_EVENT_PAL_TAG_NIDOKING_SHINY,
    [SPECIES_CLEFAIRY] = OBJ_EVENT_PAL_TAG_CLEFAIRY_SHINY,
    [SPECIES_CLEFABLE] = OBJ_EVENT_PAL_TAG_CLEFABLE_SHINY,
    [SPECIES_VULPIX] = OBJ_EVENT_PAL_TAG_VULPIX_SHINY,
    [SPECIES_NINETALES] = OBJ_EVENT_PAL_TAG_NINETALES_SHINY,
    [SPECIES_JIGGLYPUFF] = OBJ_EVENT_PAL_TAG_JIGGLYPUFF_SHINY,
    [SPECIES_WIGGLYTUFF] = OBJ_EVENT_PAL_TAG_WIGGLYTUFF_SHINY,
    [SPECIES_ZUBAT] = OBJ_EVENT_PAL_TAG_ZUBAT_SHINY,
    [SPECIES_GOLBAT] = OBJ_EVENT_PAL_TAG_GOLBAT_SHINY,
    [SPECIES_ODDISH] = OBJ_EVENT_PAL_TAG_ODDISH_SHINY,
    [SPECIES_GLOOM] = OBJ_EVENT_PAL_TAG_GLOOM_SHINY,
    [SPECIES_VILEPLUME] = OBJ_EVENT_PAL_TAG_VILEPLUME_SHINY,
    [SPECIES_PARAS] = OBJ_EVENT_PAL_TAG_PARAS_SHINY,
    [SPECIES_PARASECT] = OBJ_EVENT_PAL_TAG_PARASECT_SHINY,
    [SPECIES_VENONAT] = OBJ_EVENT_PAL_TAG_VENONAT_SHINY,
    [SPECIES_VENOMOTH] = OBJ_EVENT_PAL_TAG_VENOMOTH_SHINY,
    [SPECIES_DIGLETT] = OBJ_EVENT_PAL_TAG_DIGLETT_SHINY,
    [SPECIES_DUGTRIO] = OBJ_EVENT_PAL_TAG_DUGTRIO_SHINY,
    [SPECIES_MEOWTH] = OBJ_EVENT_PAL_TAG_MEOWTH_SHINY,
    [SPECIES_PERSIAN] = OBJ_EVENT_PAL_TAG_PERSIAN_SHINY,
    [SPECIES_PSYDUCK] = OBJ_EVENT_PAL_TAG_PSYDUCK_SHINY,
    [SPECIES_GOLDUCK] = OBJ_EVENT_PAL_TAG_GOLDUCK_SHINY,
    [SPECIES_MANKEY] = OBJ_EVENT_PAL_TAG_MANKEY_SHINY,
    [SPECIES_PRIMEAPE] = OBJ_EVENT_PAL_TAG_PRIMEAPE_SHINY,
    [SPECIES_GROWLITHE] = OBJ_EVENT_PAL_TAG_GROWLITHE_SHINY,
    [SPECIES_ARCANINE] = OBJ_EVENT_PAL_TAG_ARCANINE_SHINY,
    [SPECIES_POLIWAG] = OBJ_EVENT_PAL_TAG_POLIWAG_SHINY,
    [SPECIES_POLIWHIRL] = OBJ_EVENT_PAL_TAG_POLIWHIRL_SHINY,
    [SPECIES_POLIWRATH] = OBJ_EVENT_PAL_TAG_POLIWRATH_SHINY,
    [SPECIES_ABRA] = OBJ_EVENT_PAL_TAG_ABRA_SHINY,
    [SPECIES_KADABRA] = OBJ_EVENT_PAL_TAG_KADABRA_SHINY,
    [SPECIES_ALAKAZAM] = OBJ_EVENT_PAL_TAG_ALAKAZAM_SHINY,
    [SPECIES_MACHOP] = OBJ_EVENT_PAL_TAG_MACHOP_SHINY,
    [SPECIES_MACHOKE] = OBJ_EVENT_PAL_TAG_MACHOKE_SHINY,
    [SPECIES_MACHAMP] = OBJ_EVENT_PAL_TAG_MACHAMP_SHINY,
    [SPECIES_BELLSPROUT] = OBJ_EVENT_PAL_TAG_BELLSPROUT_SHINY,
    [SPECIES_WEEPINBELL] = OBJ_EVENT_PAL_TAG_WEEPINBELL_SHINY,
    [SPECIES_VICTREEBEL] = OBJ_EVENT_PAL_TAG_VICTREEBEL_SHINY,
    [SPECIES_TENTACOOL] = OBJ_EVENT_PAL_TAG_TENTACOOL_SHINY,
    [SPECIES_TENTACRUEL] = OBJ_EVENT_PAL_TAG_TENTACRUEL_SHINY,
    [SPECIES_GEODUDE] = OBJ_EVENT_PAL_TAG_GEODUDE_SHINY,
    [SPECIES_GRAVELER] = OBJ_EVENT_PAL_TAG_GRAVELER_SHINY,
    [SPECIES_GOLEM] = OBJ_EVENT_PAL_TAG_GOLEM_SHINY,
    [SPECIES_PONYTA] = OBJ_EVENT_PAL_TAG_PONYTA_SHINY,
    [SPECIES_RAPIDASH] = OBJ_EVENT_PAL_TAG_RAPIDASH_SHINY,
    [SPECIES_SLOWPOKE] = OBJ_EVENT_PAL_TAG_SLOWPOKE_SHINY,
    [SPECIES_SLOWBRO] = OBJ_EVENT_PAL_TAG_SLOWBRO_SHINY,
    [SPECIES_MAGNEMITE] = OBJ_EVENT_PAL_TAG_MAGNEMITE_SHINY,
    [SPECIES_MAGNETON] = OBJ_EVENT_PAL_TAG_MAGNETON_SHINY,
    [SPECIES_FARFETCHD] = OBJ_EVENT_PAL_TAG_FARFETCHD_SHINY,
    [SPECIES_DODUO] = OBJ_EVENT_PAL_TAG_DODUO_SHINY,
    [SPECIES_DODRIO] = OBJ_EVENT_PAL_TAG_DODRIO_SHINY,
    [SPECIES_SEEL] = OBJ_EVENT_PAL_TAG_SEEL_SHINY,
    [SPECIES_DEWGONG] = OBJ_EVENT_PAL_TAG_DEWGONG_SHINY,
    [SPECIES_GRIMER] = OBJ_EVENT_PAL_TAG_GRIMER_SHINY,
    [SPECIES_MUK] = OBJ_EVENT_PAL_TAG_MUK_SHINY,
    [SPECIES_SHELLDER] = OBJ_EVENT_PAL_TAG_SHELLDER_SHINY,
    [SPECIES_CLOYSTER] = OBJ_EVENT_PAL_TAG_CLOYSTER_SHINY,
    [SPECIES_GASTLY] = OBJ_EVENT_PAL_TAG_GASTLY_SHINY,
    [SPECIES_HAUNTER] = OBJ_EVENT_PAL_TAG_HAUNTER_SHINY,
    [SPECIES_GENGAR] = OBJ_EVENT_PAL_TAG_GENGAR_SHINY,
    [SPECIES_ONIX] = OBJ_EVENT_PAL_TAG_ONIX_SHINY,
    [SPECIES_DROWZEE] = OBJ_EVENT_PAL_TAG_DROWZEE_SHINY,
    [SPECIES_HYPNO] = OBJ_EVENT_PAL_TAG_HYPNO_SHINY,
    [SPECIES_KRABBY] = OBJ_EVENT_PAL_TAG_KRABBY_SHINY,
    [SPECIES_KINGLER] = OBJ_EVENT_PAL_TAG_KINGLER_SHINY,
    [SPECIES_VOLTORB] = OBJ_EVENT_PAL_TAG_VOLTORB_SHINY,
    [SPECIES_ELECTRODE] = OBJ_EVENT_PAL_TAG_ELECTRODE_SHINY,
    [SPECIES_EXEGGCUTE] = OBJ_EVENT_PAL_TAG_EXEGGCUTE_SHINY,
    [SPECIES_EXEGGUTOR] = OBJ_EVENT_PAL_TAG_EXEGGUTOR_SHINY,
    [SPECIES_CUBONE] = OBJ_EVENT_PAL_TAG_CUBONE_SHINY,
    [SPECIES_MAROWAK] = OBJ_EVENT_PAL_TAG_MAROWAK_SHINY,
    [SPECIES_HITMONLEE] = OBJ_EVENT_PAL_TAG_HITMONLEE_SHINY,
    [SPECIES_HITMONCHAN] = OBJ_EVENT_PAL_TAG_HITMONCHAN_SHINY,
    [SPECIES_LICKITUNG] = OBJ_EVENT_PAL_TAG_LICKITUNG_SHINY,
    [SPECIES_KOFFING] = OBJ_EVENT_PAL_TAG_KOFFING_SHINY,
    [SPECIES_WEEZING] = OBJ_EVENT_PAL_TAG_WEEZING_SHINY,
    [SPECIES_RHYHORN] = OBJ_EVENT_PAL_TAG_RHYHORN_SHINY,
    [SPECIES_RHYDON] = OBJ_EVENT_PAL_TAG_RHYDON_SHINY,
    [SPECIES_CHANSEY] = OBJ_EVENT_PAL_TAG_CHANSEY_SHINY,
    [SPECIES_TANGELA] = OBJ_EVENT_PAL_TAG_TANGELA_SHINY,
    [SPECIES_KANGASKHAN] = OBJ_EVENT_PAL_TAG_KANGASKHAN_SHINY,
    [SPECIES_HORSEA] = OBJ_EVENT_PAL_TAG_HORSEA_SHINY,
    [SPECIES_SEADRA] = OBJ_EVENT_PAL_TAG_SEADRA_SHINY,
    [SPECIES_GOLDEEN] = OBJ_EVENT_PAL_TAG_GOLDEEN_SHINY,
    [SPECIES_SEAKING] = OBJ_EVENT_PAL_TAG_SEAKING_SHINY,
    [SPECIES_STARYU] = OBJ_EVENT_PAL_TAG_STARYU_SHINY,
    [SPECIES_STARMIE] = OBJ_EVENT_PAL_TAG_STARMIE_SHINY,
    [SPECIES_MR_MIME] = OBJ_EVENT_PAL_TAG_MR_MIME_SHINY,
    [SPECIES_SCYTHER] = OBJ_EVENT_PAL_TAG_SCYTHER_SHINY,
    [SPECIES_JYNX] = OBJ_EVENT_PAL_TAG_JYNX_SHINY,
    [SPECIES_ELECTABUZZ] = OBJ_EVENT_PAL_TAG_ELECTABUZZ_SHINY,
    [SPECIES_MAGMAR] = OBJ_EVENT_PAL_TAG_MAGMAR_SHINY,
    [SPECIES_PINSIR] = OBJ_EVENT_PAL_TAG_PINSIR_SHINY,
    [SPECIES_TAUROS] = OBJ_EVENT_PAL_TAG_TAUROS_SHINY,
    [SPECIES_MAGIKARP] = OBJ_EVENT_PAL_TAG_MAGIKARP_SHINY,
    [SPECIES_GYARADOS] = OBJ_EVENT_PAL_TAG_GYARADOS_SHINY,
    [SPECIES_LAPRAS] = OBJ_EVENT_PAL_TAG_LAPRAS_SHINY,
    [SPECIES_DITTO] = OBJ_EVENT_PAL_TAG_DITTO_SHINY,
    [SPECIES_EEVEE] = OBJ_EVENT_PAL_TAG_EEVEE_SHINY,
    [SPECIES_VAPOREON] = OBJ_EVENT_PAL_TAG_VAPOREON_SHINY,
    [SPECIES_JOLTEON] = OBJ_EVENT_PAL_TAG_JOLTEON_SHINY,
    [SPECIES_FLAREON] = OBJ_EVENT_PAL_TAG_FLAREON_SHINY,
    [SPECIES_PORYGON] = OBJ_EVENT_PAL_TAG_PORYGON_SHINY,
    [SPECIES_OMANYTE] = OBJ_EVENT_PAL_TAG_OMANYTE_SHINY,
    [SPECIES_OMASTAR] = OBJ_EVENT_PAL_TAG_OMASTAR_SHINY,
    [SPECIES_KABUTO] = OBJ_EVENT_PAL_TAG_KABUTO_SHINY,
    [SPECIES_KABUTOPS] = OBJ_EVENT_PAL_TAG_KABUTOPS_SHINY,
    [SPECIES_AERODACTYL] = OBJ_EVENT_PAL_TAG_AERODACTYL_SHINY,
    [SPECIES_SNORLAX] = OBJ_EVENT_PAL_TAG_SNORLAX_SHINY,
    [SPECIES_ARTICUNO] = OBJ_EVENT_PAL_TAG_ARTICUNO_SHINY,
    [SPECIES_ZAPDOS] = OBJ_EVENT_PAL_TAG_ZAPDOS_SHINY,
    [SPECIES_MOLTRES] = OBJ_EVENT_PAL_TAG_MOLTRES_SHINY,
    [SPECIES_DRATINI] = OBJ_EVENT_PAL_TAG_DRATINI_SHINY,
    [SPECIES_DRAGONAIR] = OBJ_EVENT_PAL_TAG_DRAGONAIR_SHINY,
    [SPECIES_DRAGONITE] = OBJ_EVENT_PAL_TAG_DRAGONITE_SHINY,
    [SPECIES_MEWTWO] = OBJ_EVENT_PAL_TAG_MEWTWO_SHINY,
    [SPECIES_MEW] = OBJ_EVENT_PAL_TAG_MEW_SHINY,
    [SPECIES_CHIKORITA] = OBJ_EVENT_PAL_TAG_CHIKORITA_SHINY,
    [SPECIES_BAYLEEF] = OBJ_EVENT_PAL_TAG_BAYLEEF_SHINY,
    [SPECIES_MEGANIUM] = OBJ_EVENT_PAL_TAG_MEGANIUM_SHINY,
    [SPECIES_CYNDAQUIL] = OBJ_EVENT_PAL_TAG_CYNDAQUIL_SHINY,
    [SPECIES_QUILAVA] = OBJ_EVENT_PAL_TAG_QUILAVA_SHINY,
    [SPECIES_TYPHLOSION] = OBJ_EVENT_PAL_TAG_TYPHLOSION_SHINY,
    [SPECIES_TOTODILE] = OBJ_EVENT_PAL_TAG_TOTODILE_SHINY,
    [SPECIES_CROCONAW] = OBJ_EVENT_PAL_TAG_CROCONAW_SHINY,
    [SPECIES_FERALIGATR] = OBJ_EVENT_PAL_TAG_FERALIGATR_SHINY,
    [SPECIES_SENTRET] = OBJ_EVENT_PAL_TAG_SENTRET_SHINY,
    [SPECIES_FURRET] = OBJ_EVENT_PAL_TAG_FURRET_SHINY,
    [SPECIES_HOOTHOOT] = OBJ_EVENT_PAL_TAG_HOOTHOOT_SHINY,
    [SPECIES_NOCTOWL] = OBJ_EVENT_PAL_TAG_NOCTOWL_SHINY,
    [SPECIES_LEDYBA] = OBJ_EVENT_PAL_TAG_LEDYBA_SHINY,
    [SPECIES_LEDIAN] = OBJ_EVENT_PAL_TAG_LEDIAN_SHINY,
    [SPECIES_SPINARAK] = OBJ_EVENT_PAL_TAG_SPINARAK_SHINY,
    [SPECIES_ARIADOS] = OBJ_EVENT_PAL_TAG_ARIADOS_SHINY,
    [SPECIES_CROBAT] = OBJ_EVENT_PAL_TAG_CROBAT_SHINY,
    [SPECIES_CHINCHOU] = OBJ_EVENT_PAL_TAG_CHINCHOU_SHINY,
    [SPECIES_LANTURN] = OBJ_EVENT_PAL_TAG_LANTURN_SHINY,
    [SPECIES_PICHU] = OBJ_EVENT_PAL_TAG_PICHU_SHINY,
    [SPECIES_CLEFFA] = OBJ_EVENT_PAL_TAG_CLEFFA_SHINY,
    [SPECIES_IGGLYBUFF] = OBJ_EVENT_PAL_TAG_IGGLYBUFF_SHINY,
    [SPECIES_TOGEPI] = OBJ_EVENT_PAL_TAG_TOGEPI_SHINY,
    [SPECIES_TOGETIC] = OBJ_EVENT_PAL_TAG_TOGETIC_SHINY,
    [SPECIES_NATU] = OBJ_EVENT_PAL_TAG_NATU_SHINY,
    [SPECIES_XATU] = OBJ_EVENT_PAL_TAG_XATU_SHINY,
    [SPECIES_MAREEP] = OBJ_EVENT_PAL_TAG_MAREEP_SHINY,
    [SPECIES_FLAAFFY] = OBJ_EVENT_PAL_TAG_FLAAFFY_SHINY,
    [SPECIES_AMPHAROS] = OBJ_EVENT_PAL_TAG_AMPHAROS_SHINY,
    [SPECIES_BELLOSSOM] = OBJ_EVENT_PAL_TAG_BELLOSSOM_SHINY,
    [SPECIES_MARILL] = OBJ_EVENT_PAL_TAG_MARILL_SHINY,
    [SPECIES_AZUMARILL] = OBJ_EVENT_PAL_TAG_AZUMARILL_SHINY,
    [SPECIES_SUDOWOODO] = OBJ_EVENT_PAL_TAG_SUDOWOODO_SHINY,
    [SPECIES_POLITOED] = OBJ_EVENT_PAL_TAG_POLITOED_SHINY,
    [SPECIES_HOPPIP] = OBJ_EVENT_PAL_TAG_HOPPIP_SHINY,
    [SPECIES_SKIPLOOM] = OBJ_EVENT_PAL_TAG_SKIPLOOM_SHINY,
    [SPECIES_JUMPLUFF] = OBJ_EVENT_PAL_TAG_JUMPLUFF_SHINY,
    [SPECIES_AIPOM] = OBJ_EVENT_PAL_TAG_AIPOM_SHINY,
    [SPECIES_SUNKERN] = OBJ_EVENT_PAL_TAG_SUNKERN_SHINY,
    [SPECIES_SUNFLORA] = OBJ_EVENT_PAL_TAG_SUNFLORA_SHINY,
    [SPECIES_YANMA] = OBJ_EVENT_PAL_TAG_YANMA_SHINY,
    [SPECIES_WOOPER] = OBJ_EVENT_PAL_TAG_WOOPER_SHINY,
    [SPECIES_QUAGSIRE] = OBJ_EVENT_PAL_TAG_QUAGSIRE_SHINY,
    [SPECIES_ESPEON] = OBJ_EVENT_PAL_TAG_ESPEON_SHINY,
    [SPECIES_UMBREON] = OBJ_EVENT_PAL_TAG_UMBREON_SHINY,
    [SPECIES_MURKROW] = OBJ_EVENT_PAL_TAG_MURKROW_SHINY,
    [SPECIES_SLOWKING] = OBJ_EVENT_PAL_TAG_SLOWKING_SHINY,
    [SPECIES_MISDREAVUS] = OBJ_EVENT_PAL_TAG_MISDREAVUS_SHINY,
    [SPECIES_UNOWN] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_WOBBUFFET] = OBJ_EVENT_PAL_TAG_WOBBUFFET_SHINY,
    [SPECIES_GIRAFARIG] = OBJ_EVENT_PAL_TAG_GIRAFARIG_SHINY,
    [SPECIES_PINECO] = OBJ_EVENT_PAL_TAG_PINECO_SHINY,
    [SPECIES_FORRETRESS] = OBJ_EVENT_PAL_TAG_FORRETRESS_SHINY,
    [SPECIES_DUNSPARCE] = OBJ_EVENT_PAL_TAG_DUNSPARCE_SHINY,
    [SPECIES_GLIGAR] = OBJ_EVENT_PAL_TAG_GLIGAR_SHINY,
    [SPECIES_STEELIX] = OBJ_EVENT_PAL_TAG_STEELIX_SHINY,
    [SPECIES_SNUBBULL] = OBJ_EVENT_PAL_TAG_SNUBBULL_SHINY,
    [SPECIES_GRANBULL] = OBJ_EVENT_PAL_TAG_GRANBULL_SHINY,
    [SPECIES_QWILFISH] = OBJ_EVENT_PAL_TAG_QWILFISH_SHINY,
    [SPECIES_SCIZOR] = OBJ_EVENT_PAL_TAG_SCIZOR_SHINY,
    [SPECIES_SHUCKLE] = OBJ_EVENT_PAL_TAG_SHUCKLE_SHINY,
    [SPECIES_HERACROSS] = OBJ_EVENT_PAL_TAG_HERACROSS_SHINY,
    [SPECIES_SNEASEL] = OBJ_EVENT_PAL_TAG_SNEASEL_SHINY,
    [SPECIES_TEDDIURSA] = OBJ_EVENT_PAL_TAG_TEDDIURSA_SHINY,
    [SPECIES_URSARING] = OBJ_EVENT_PAL_TAG_URSARING_SHINY,
    [SPECIES_SLUGMA] = OBJ_EVENT_PAL_TAG_SLUGMA_SHINY,
    [SPECIES_MAGCARGO] = OBJ_EVENT_PAL_TAG_MAGCARGO_SHINY,
    [SPECIES_SWINUB] = OBJ_EVENT_PAL_TAG_SWINUB_SHINY,
    [SPECIES_PILOSWINE] = OBJ_EVENT_PAL_TAG_PILOSWINE_SHINY,
    [SPECIES_CORSOLA] = OBJ_EVENT_PAL_TAG_CORSOLA_SHINY,
    [SPECIES_REMORAID] = OBJ_EVENT_PAL_TAG_REMORAID_SHINY,
    [SPECIES_OCTILLERY] = OBJ_EVENT_PAL_TAG_OCTILLERY_SHINY,
    [SPECIES_DELIBIRD] = OBJ_EVENT_PAL_TAG_DELIBIRD_SHINY,
    [SPECIES_MANTINE] = OBJ_EVENT_PAL_TAG_MANTINE_SHINY,
    [SPECIES_SKARMORY] = OBJ_EVENT_PAL_TAG_SKARMORY_SHINY,
    [SPECIES_HOUNDOUR] = OBJ_EVENT_PAL_TAG_HOUNDOUR_SHINY,
    [SPECIES_HOUNDOOM] = OBJ_EVENT_PAL_TAG_HOUNDOOM_SHINY,
    [SPECIES_KINGDRA] = OBJ_EVENT_PAL_TAG_KINGDRA_SHINY,
    [SPECIES_PHANPY] = OBJ_EVENT_PAL_TAG_PHANPY_SHINY,
    [SPECIES_DONPHAN] = OBJ_EVENT_PAL_TAG_DONPHAN_SHINY,
    [SPECIES_PORYGON2] = OBJ_EVENT_PAL_TAG_PORYGON2_SHINY,
    [SPECIES_STANTLER] = OBJ_EVENT_PAL_TAG_STANTLER_SHINY,
    [SPECIES_SMEARGLE] = OBJ_EVENT_PAL_TAG_SMEARGLE_SHINY,
    [SPECIES_TYROGUE] = OBJ_EVENT_PAL_TAG_TYROGUE_SHINY,
    [SPECIES_HITMONTOP] = OBJ_EVENT_PAL_TAG_HITMONTOP_SHINY,
    [SPECIES_SMOOCHUM] = OBJ_EVENT_PAL_TAG_SMOOCHUM_SHINY,
    [SPECIES_ELEKID] = OBJ_EVENT_PAL_TAG_ELEKID_SHINY,
    [SPECIES_MAGBY] = OBJ_EVENT_PAL_TAG_MAGBY_SHINY,
    [SPECIES_MILTANK] = OBJ_EVENT_PAL_TAG_MILTANK_SHINY,
    [SPECIES_BLISSEY] = OBJ_EVENT_PAL_TAG_BLISSEY_SHINY,
    [SPECIES_RAIKOU] = OBJ_EVENT_PAL_TAG_RAIKOU_SHINY,
    [SPECIES_ENTEI] = OBJ_EVENT_PAL_TAG_ENTEI_SHINY,
    [SPECIES_SUICUNE] = OBJ_EVENT_PAL_TAG_SUICUNE_SHINY,
    [SPECIES_LARVITAR] = OBJ_EVENT_PAL_TAG_LARVITAR_SHINY,
    [SPECIES_PUPITAR] = OBJ_EVENT_PAL_TAG_PUPITAR_SHINY,
    [SPECIES_TYRANITAR] = OBJ_EVENT_PAL_TAG_TYRANITAR_SHINY,
    [SPECIES_LUGIA] = OBJ_EVENT_PAL_TAG_LUGIA_SHINY,
    [SPECIES_HO_OH] = OBJ_EVENT_PAL_TAG_HO_OH_SHINY,
    [SPECIES_CELEBI] = OBJ_EVENT_PAL_TAG_CELEBI_SHINY,
    [SPECIES_TREECKO] = OBJ_EVENT_PAL_TAG_TREECKO_SHINY,
    [SPECIES_GROVYLE] = OBJ_EVENT_PAL_TAG_GROVYLE_SHINY,
    [SPECIES_SCEPTILE] = OBJ_EVENT_PAL_TAG_SCEPTILE_SHINY,
    [SPECIES_TORCHIC] = OBJ_EVENT_PAL_TAG_TORCHIC_SHINY,
    [SPECIES_COMBUSKEN] = OBJ_EVENT_PAL_TAG_COMBUSKEN_SHINY,
    [SPECIES_BLAZIKEN] = OBJ_EVENT_PAL_TAG_BLAZIKEN_SHINY,
    [SPECIES_MUDKIP] = OBJ_EVENT_PAL_TAG_MUDKIP_SHINY,
    [SPECIES_MARSHTOMP] = OBJ_EVENT_PAL_TAG_MARSHTOMP_SHINY,
    [SPECIES_SWAMPERT] = OBJ_EVENT_PAL_TAG_SWAMPERT_SHINY,
    [SPECIES_POOCHYENA] = OBJ_EVENT_PAL_TAG_POOCHYENA_SHINY,
    [SPECIES_MIGHTYENA] = OBJ_EVENT_PAL_TAG_MIGHTYENA_SHINY,
    [SPECIES_ZIGZAGOON] = OBJ_EVENT_PAL_TAG_ZIGZAGOON_SHINY,
    [SPECIES_LINOONE] = OBJ_EVENT_PAL_TAG_LINOONE_SHINY,
    [SPECIES_WURMPLE] = OBJ_EVENT_PAL_TAG_WURMPLE_SHINY,
    [SPECIES_SILCOON] = OBJ_EVENT_PAL_TAG_SILCOON_SHINY,
    [SPECIES_BEAUTIFLY] = OBJ_EVENT_PAL_TAG_BEAUTIFLY_SHINY,
    [SPECIES_CASCOON] = OBJ_EVENT_PAL_TAG_CASCOON_SHINY,
    [SPECIES_DUSTOX] = OBJ_EVENT_PAL_TAG_DUSTOX_SHINY,
    [SPECIES_LOTAD] = OBJ_EVENT_PAL_TAG_LOTAD_SHINY,
    [SPECIES_LOMBRE] = OBJ_EVENT_PAL_TAG_LOMBRE_SHINY,
    [SPECIES_LUDICOLO] = OBJ_EVENT_PAL_TAG_LUDICOLO_SHINY,
    [SPECIES_SEEDOT] = OBJ_EVENT_PAL_TAG_SEEDOT_SHINY,
    [SPECIES_NUZLEAF] = OBJ_EVENT_PAL_TAG_NUZLEAF_SHINY,
    [SPECIES_SHIFTRY] = OBJ_EVENT_PAL_TAG_SHIFTRY_SHINY,
    [SPECIES_NINCADA] = OBJ_EVENT_PAL_TAG_NINCADA_SHINY,
    [SPECIES_NINJASK] = OBJ_EVENT_PAL_TAG_NINJASK_SHINY,
    [SPECIES_SHEDINJA] = OBJ_EVENT_PAL_TAG_SHEDINJA_SHINY,
    [SPECIES_TAILLOW] = OBJ_EVENT_PAL_TAG_TAILLOW_SHINY,
    [SPECIES_SWELLOW] = OBJ_EVENT_PAL_TAG_SWELLOW_SHINY,
    [SPECIES_SHROOMISH] = OBJ_EVENT_PAL_TAG_SHROOMISH_SHINY,
    [SPECIES_BRELOOM] = OBJ_EVENT_PAL_TAG_BRELOOM_SHINY,
    [SPECIES_SPINDA] = OBJ_EVENT_PAL_TAG_SPINDA_SHINY,
    [SPECIES_WINGULL] = OBJ_EVENT_PAL_TAG_WINGULL_SHINY,
    [SPECIES_PELIPPER] = OBJ_EVENT_PAL_TAG_PELIPPER_SHINY,
    [SPECIES_SURSKIT] = OBJ_EVENT_PAL_TAG_SURSKIT_SHINY,
    [SPECIES_MASQUERAIN] = OBJ_EVENT_PAL_TAG_MASQUERAIN_SHINY,
    [SPECIES_WAILMER] = OBJ_EVENT_PAL_TAG_WAILMER_SHINY,
    [SPECIES_WAILORD] = OBJ_EVENT_PAL_TAG_WAILORD_SHINY,
    [SPECIES_SKITTY] = OBJ_EVENT_PAL_TAG_SKITTY_SHINY,
    [SPECIES_DELCATTY] = OBJ_EVENT_PAL_TAG_DELCATTY_SHINY,
    [SPECIES_KECLEON] = OBJ_EVENT_PAL_TAG_KECLEON_SHINY,
    [SPECIES_BALTOY] = OBJ_EVENT_PAL_TAG_BALTOY_SHINY,
    [SPECIES_CLAYDOL] = OBJ_EVENT_PAL_TAG_CLAYDOL_SHINY,
    [SPECIES_NOSEPASS] = OBJ_EVENT_PAL_TAG_NOSEPASS_SHINY,
    [SPECIES_TORKOAL] = OBJ_EVENT_PAL_TAG_TORKOAL_SHINY,
    [SPECIES_SABLEYE] = OBJ_EVENT_PAL_TAG_SABLEYE_SHINY,
    [SPECIES_BARBOACH] = OBJ_EVENT_PAL_TAG_BARBOACH_SHINY,
    [SPECIES_WHISCASH] = OBJ_EVENT_PAL_TAG_WHISCASH_SHINY,
    [SPECIES_LUVDISC] = OBJ_EVENT_PAL_TAG_LUVDISC_SHINY,
    [SPECIES_CORPHISH] = OBJ_EVENT_PAL_TAG_CORPHISH_SHINY,
    [SPECIES_CRAWDAUNT] = OBJ_EVENT_PAL_TAG_CRAWDAUNT_SHINY,
    [SPECIES_FEEBAS] = OBJ_EVENT_PAL_TAG_FEEBAS_SHINY,
    [SPECIES_MILOTIC] = OBJ_EVENT_PAL_TAG_MILOTIC_SHINY,
    [SPECIES_CARVANHA] = OBJ_EVENT_PAL_TAG_CARVANHA_SHINY,
    [SPECIES_SHARPEDO] = OBJ_EVENT_PAL_TAG_SHARPEDO_SHINY,
    [SPECIES_TRAPINCH] = OBJ_EVENT_PAL_TAG_TRAPINCH_SHINY,
    [SPECIES_VIBRAVA] = OBJ_EVENT_PAL_TAG_VIBRAVA_SHINY,
    [SPECIES_FLYGON] = OBJ_EVENT_PAL_TAG_FLYGON_SHINY,
    [SPECIES_MAKUHITA] = OBJ_EVENT_PAL_TAG_MAKUHITA_SHINY,
    [SPECIES_HARIYAMA] = OBJ_EVENT_PAL_TAG_HARIYAMA_SHINY,
    [SPECIES_ELECTRIKE] = OBJ_EVENT_PAL_TAG_ELECTRIKE_SHINY,
    [SPECIES_MANECTRIC] = OBJ_EVENT_PAL_TAG_MANECTRIC_SHINY,
    [SPECIES_NUMEL] = OBJ_EVENT_PAL_TAG_NUMEL_SHINY,
    [SPECIES_CAMERUPT] = OBJ_EVENT_PAL_TAG_CAMERUPT_SHINY,
    [SPECIES_SPHEAL] = OBJ_EVENT_PAL_TAG_SPHEAL_SHINY,
    [SPECIES_SEALEO] = OBJ_EVENT_PAL_TAG_SEALEO_SHINY,
    [SPECIES_WALREIN] = OBJ_EVENT_PAL_TAG_WALREIN_SHINY,
    [SPECIES_CACNEA] = OBJ_EVENT_PAL_TAG_CACNEA_SHINY,
    [SPECIES_CACTURNE] = OBJ_EVENT_PAL_TAG_CACTURNE_SHINY,
    [SPECIES_SNORUNT] = OBJ_EVENT_PAL_TAG_SNORUNT_SHINY,
    [SPECIES_GLALIE] = OBJ_EVENT_PAL_TAG_GLALIE_SHINY,
    [SPECIES_LUNATONE] = OBJ_EVENT_PAL_TAG_LUNATONE_SHINY,
    [SPECIES_SOLROCK] = OBJ_EVENT_PAL_TAG_SOLROCK_SHINY,
    [SPECIES_AZURILL] = OBJ_EVENT_PAL_TAG_AZURILL_SHINY,
    [SPECIES_SPOINK] = OBJ_EVENT_PAL_TAG_SPOINK_SHINY,
    [SPECIES_GRUMPIG] = OBJ_EVENT_PAL_TAG_GRUMPIG_SHINY,
    [SPECIES_PLUSLE] = OBJ_EVENT_PAL_TAG_PLUSLE_SHINY,
    [SPECIES_MINUN] = OBJ_EVENT_PAL_TAG_MINUN_SHINY,
    [SPECIES_MAWILE] = OBJ_EVENT_PAL_TAG_MAWILE_SHINY,
    [SPECIES_MEDITITE] = OBJ_EVENT_PAL_TAG_MEDITITE_SHINY,
    [SPECIES_MEDICHAM] = OBJ_EVENT_PAL_TAG_MEDICHAM_SHINY,
    [SPECIES_SWABLU] = OBJ_EVENT_PAL_TAG_SWABLU_SHINY,
    [SPECIES_ALTARIA] = OBJ_EVENT_PAL_TAG_ALTARIA_SHINY,
    [SPECIES_WYNAUT] = OBJ_EVENT_PAL_TAG_WYNAUT_SHINY,
    [SPECIES_DUSKULL] = OBJ_EVENT_PAL_TAG_DUSKULL_SHINY,
    [SPECIES_DUSCLOPS] = OBJ_EVENT_PAL_TAG_DUSCLOPS_SHINY,
    [SPECIES_ROSELIA] = OBJ_EVENT_PAL_TAG_ROSELIA_SHINY,
    [SPECIES_SLAKOTH] = OBJ_EVENT_PAL_TAG_SLAKOTH_SHINY,
    [SPECIES_VIGOROTH] = OBJ_EVENT_PAL_TAG_VIGOROTH_SHINY,
    [SPECIES_SLAKING] = OBJ_EVENT_PAL_TAG_SLAKING_SHINY,
    [SPECIES_GULPIN] = OBJ_EVENT_PAL_TAG_GULPIN_SHINY,
    [SPECIES_SWALOT] = OBJ_EVENT_PAL_TAG_SWALOT_SHINY,
    [SPECIES_TROPIUS] = OBJ_EVENT_PAL_TAG_TROPIUS_SHINY,
    [SPECIES_WHISMUR] = OBJ_EVENT_PAL_TAG_WHISMUR_SHINY,
    [SPECIES_LOUDRED] = OBJ_EVENT_PAL_TAG_LOUDRED_SHINY,
    [SPECIES_EXPLOUD] = OBJ_EVENT_PAL_TAG_EXPLOUD_SHINY,
    [SPECIES_CLAMPERL] = OBJ_EVENT_PAL_TAG_CLAMPERL_SHINY,
    [SPECIES_HUNTAIL] = OBJ_EVENT_PAL_TAG_HUNTAIL_SHINY,
    [SPECIES_GOREBYSS] = OBJ_EVENT_PAL_TAG_GOREBYSS_SHINY,
    [SPECIES_ABSOL] = OBJ_EVENT_PAL_TAG_ABSOL_SHINY,
    [SPECIES_SHUPPET] = OBJ_EVENT_PAL_TAG_SHUPPET_SHINY,
    [SPECIES_BANETTE] = OBJ_EVENT_PAL_TAG_BANETTE_SHINY,
    [SPECIES_SEVIPER] = OBJ_EVENT_PAL_TAG_SEVIPER_SHINY,
    [SPECIES_ZANGOOSE] = OBJ_EVENT_PAL_TAG_ZANGOOSE_SHINY,
    [SPECIES_RELICANTH] = OBJ_EVENT_PAL_TAG_RELICANTH_SHINY,
    [SPECIES_ARON] = OBJ_EVENT_PAL_TAG_ARON_SHINY,
    [SPECIES_LAIRON] = OBJ_EVENT_PAL_TAG_LAIRON_SHINY,
    [SPECIES_AGGRON] = OBJ_EVENT_PAL_TAG_AGGRON_SHINY,
    [SPECIES_CASTFORM] = OBJ_EVENT_PAL_TAG_CASTFORM_SHINY,
    [SPECIES_VOLBEAT] = OBJ_EVENT_PAL_TAG_VOLBEAT_SHINY,
    [SPECIES_ILLUMISE] = OBJ_EVENT_PAL_TAG_ILLUMISE_SHINY,
    [SPECIES_LILEEP] = OBJ_EVENT_PAL_TAG_LILEEP_SHINY,
    [SPECIES_CRADILY] = OBJ_EVENT_PAL_TAG_CRADILY_SHINY,
    [SPECIES_ANORITH] = OBJ_EVENT_PAL_TAG_ANORITH_SHINY,
    [SPECIES_ARMALDO] = OBJ_EVENT_PAL_TAG_ARMALDO_SHINY,
    [SPECIES_RALTS] = OBJ_EVENT_PAL_TAG_RALTS_SHINY,
    [SPECIES_KIRLIA] = OBJ_EVENT_PAL_TAG_KIRLIA_SHINY,
    [SPECIES_GARDEVOIR] = OBJ_EVENT_PAL_TAG_GARDEVOIR_SHINY,
    [SPECIES_BAGON] = OBJ_EVENT_PAL_TAG_BAGON_SHINY,
    [SPECIES_SHELGON] = OBJ_EVENT_PAL_TAG_SHELGON_SHINY,
    [SPECIES_SALAMENCE] = OBJ_EVENT_PAL_TAG_SALAMENCE_SHINY,
    [SPECIES_BELDUM] = OBJ_EVENT_PAL_TAG_BELDUM_SHINY,
    [SPECIES_METANG] = OBJ_EVENT_PAL_TAG_METANG_SHINY,
    [SPECIES_METAGROSS] = OBJ_EVENT_PAL_TAG_METAGROSS_SHINY,
    [SPECIES_REGIROCK] = OBJ_EVENT_PAL_TAG_REGIROCK_SHINY,
    [SPECIES_REGICE] = OBJ_EVENT_PAL_TAG_REGICE_SHINY,
    [SPECIES_REGISTEEL] = OBJ_EVENT_PAL_TAG_REGISTEEL_SHINY,
    [SPECIES_KYOGRE] = OBJ_EVENT_PAL_TAG_KYOGRE_SHINY,
    [SPECIES_GROUDON] = OBJ_EVENT_PAL_TAG_GROUDON_SHINY,
    [SPECIES_RAYQUAZA] = OBJ_EVENT_PAL_TAG_RAYQUAZA_SHINY,
    [SPECIES_LATIAS] = OBJ_EVENT_PAL_TAG_LATIAS_SHINY,
    [SPECIES_LATIOS] = OBJ_EVENT_PAL_TAG_LATIOS_SHINY,
    [SPECIES_JIRACHI] = OBJ_EVENT_PAL_TAG_JIRACHI_SHINY,
    [SPECIES_DEOXYS] = OBJ_EVENT_PAL_TAG_DEOXYS_SHINY,
    [SPECIES_CHIMECHO] = OBJ_EVENT_PAL_TAG_CHIMECHO_SHINY,
    [SPECIES_UNOWN_B] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_C] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_D] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_E] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_F] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_G] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_H] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_I] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_J] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_K] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_L] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_M] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_N] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_O] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_P] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_Q] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_R] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_S] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_T] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_U] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_V] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_W] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_X] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_Y] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_Z] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_EXCLAMATION] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_UNOWN_QUESTION] = OBJ_EVENT_PAL_TAG_UNOWN_SHINY,
    [SPECIES_TURTWIG] = OBJ_EVENT_PAL_TAG_TURTWIG_SHINY,
    [SPECIES_GROTLE] = OBJ_EVENT_PAL_TAG_GROTLE_SHINY,
    [SPECIES_TORTERRA] = OBJ_EVENT_PAL_TAG_TORTERRA_SHINY,
    [SPECIES_CHIMCHAR] = OBJ_EVENT_PAL_TAG_CHIMCHAR_SHINY,
    [SPECIES_MONFERNO] = OBJ_EVENT_PAL_TAG_MONFERNO_SHINY,
    [SPECIES_INFERNAPE] = OBJ_EVENT_PAL_TAG_INFERNAPE_SHINY,
    [SPECIES_PIPLUP] = OBJ_EVENT_PAL_TAG_PIPLUP_SHINY,
    [SPECIES_PRINPLUP] = OBJ_EVENT_PAL_TAG_PRINPLUP_SHINY,
    [SPECIES_EMPOLEON] = OBJ_EVENT_PAL_TAG_EMPOLEON_SHINY,
    [SPECIES_STARLY] = OBJ_EVENT_PAL_TAG_STARLY_SHINY,
    [SPECIES_STARAVIA] = OBJ_EVENT_PAL_TAG_STARAVIA_SHINY,
    [SPECIES_STARAPTOR] = OBJ_EVENT_PAL_TAG_STARAPTOR_SHINY,
    [SPECIES_BIDOOF] = OBJ_EVENT_PAL_TAG_BIDOOF_SHINY,
    [SPECIES_BIBAREL] = OBJ_EVENT_PAL_TAG_BIBAREL_SHINY,
    [SPECIES_KRICKETOT] = OBJ_EVENT_PAL_TAG_KRICKETOT_SHINY,
    [SPECIES_KRICKETUNE] = OBJ_EVENT_PAL_TAG_KRICKETUNE_SHINY,
    [SPECIES_SHINX] = OBJ_EVENT_PAL_TAG_SHINX_SHINY,
    [SPECIES_LUXIO] = OBJ_EVENT_PAL_TAG_LUXIO_SHINY,
    [SPECIES_LUXRAY] = OBJ_EVENT_PAL_TAG_LUXRAY_SHINY,
    [SPECIES_BUDEW] = OBJ_EVENT_PAL_TAG_BUDEW_SHINY,
    [SPECIES_ROSERADE] = OBJ_EVENT_PAL_TAG_ROSERADE_SHINY,
    [SPECIES_CRANIDOS] = OBJ_EVENT_PAL_TAG_CRANIDOS_SHINY,
    [SPECIES_RAMPARDOS] = OBJ_EVENT_PAL_TAG_RAMPARDOS_SHINY,
    [SPECIES_SHIELDON] = OBJ_EVENT_PAL_TAG_SHIELDON_SHINY,
    [SPECIES_BASTIODON] = OBJ_EVENT_PAL_TAG_BASTIODON_SHINY,
    [SPECIES_BURMY] = OBJ_EVENT_PAL_TAG_BURMY_SHINY,
    [SPECIES_WORMADAM] = OBJ_EVENT_PAL_TAG_WORMADAM_SHINY,
    [SPECIES_MOTHIM] = OBJ_EVENT_PAL_TAG_MOTHIM_SHINY,
    [SPECIES_COMBEE] = OBJ_EVENT_PAL_TAG_COMBEE_SHINY,
    [SPECIES_VESPIQUEN] = OBJ_EVENT_PAL_TAG_VESPIQUEN_SHINY,
    [SPECIES_PACHIRISU] = OBJ_EVENT_PAL_TAG_PACHIRISU_SHINY,
    [SPECIES_BUIZEL] = OBJ_EVENT_PAL_TAG_BUIZEL_SHINY,
    [SPECIES_FLOATZEL] = OBJ_EVENT_PAL_TAG_FLOATZEL_SHINY,
    [SPECIES_CHERUBI] = OBJ_EVENT_PAL_TAG_CHERUBI_SHINY,
    [SPECIES_CHERRIM] = OBJ_EVENT_PAL_TAG_CHERRIM_SHINY,
    [SPECIES_SHELLOS] = OBJ_EVENT_PAL_TAG_SHELLOS_SHINY,
    [SPECIES_GASTRODON] = OBJ_EVENT_PAL_TAG_GASTRODON_SHINY,
    [SPECIES_AMBIPOM] = OBJ_EVENT_PAL_TAG_AMBIPOM_SHINY,
    [SPECIES_DRIFLOON] = OBJ_EVENT_PAL_TAG_DRIFLOON_SHINY,
    [SPECIES_DRIFBLIM] = OBJ_EVENT_PAL_TAG_DRIFBLIM_SHINY,
    [SPECIES_BUNEARY] = OBJ_EVENT_PAL_TAG_BUNEARY_SHINY,
    [SPECIES_LOPUNNY] = OBJ_EVENT_PAL_TAG_LOPUNNY_SHINY,
    [SPECIES_MISMAGIUS] = OBJ_EVENT_PAL_TAG_MISMAGIUS_SHINY,
    [SPECIES_HONCHKROW] = OBJ_EVENT_PAL_TAG_HONCHKROW_SHINY,
    [SPECIES_GLAMEOW] = OBJ_EVENT_PAL_TAG_GLAMEOW_SHINY,
    [SPECIES_PURUGLY] = OBJ_EVENT_PAL_TAG_PURUGLY_SHINY,
    [SPECIES_CHINGLING] = OBJ_EVENT_PAL_TAG_CHINGLING_SHINY,
    [SPECIES_STUNKY] = OBJ_EVENT_PAL_TAG_STUNKY_SHINY,
    [SPECIES_SKUNTANK] = OBJ_EVENT_PAL_TAG_SKUNTANK_SHINY,
    [SPECIES_BRONZOR] = OBJ_EVENT_PAL_TAG_BRONZOR_SHINY,
    [SPECIES_BRONZONG] = OBJ_EVENT_PAL_TAG_BRONZONG_SHINY,
    [SPECIES_BONSLY] = OBJ_EVENT_PAL_TAG_BONSLY_SHINY,
    [SPECIES_MIME_JR] = OBJ_EVENT_PAL_TAG_MIME_JR_SHINY,
    [SPECIES_HAPPINY] = OBJ_EVENT_PAL_TAG_HAPPINY_SHINY,
    [SPECIES_CHATOT] = OBJ_EVENT_PAL_TAG_CHATOT_SHINY,
    [SPECIES_SPIRITOMB] = OBJ_EVENT_PAL_TAG_SPIRITOMB_SHINY,
    [SPECIES_GIBLE] = OBJ_EVENT_PAL_TAG_GIBLE_SHINY,
    [SPECIES_GABITE] = OBJ_EVENT_PAL_TAG_GABITE_SHINY,
    [SPECIES_GARCHOMP] = OBJ_EVENT_PAL_TAG_GARCHOMP_SHINY,
    [SPECIES_MUNCHLAX] = OBJ_EVENT_PAL_TAG_MUNCHLAX_SHINY,
    [SPECIES_RIOLU] = OBJ_EVENT_PAL_TAG_RIOLU_SHINY,
    [SPECIES_LUCARIO] = OBJ_EVENT_PAL_TAG_LUCARIO_SHINY,
    [SPECIES_HIPPOPOTAS] = OBJ_EVENT_PAL_TAG_HIPPOPOTAS_SHINY,
    [SPECIES_HIPPOWDON] = OBJ_EVENT_PAL_TAG_HIPPOWDON_SHINY,
    [SPECIES_SKORUPI] = OBJ_EVENT_PAL_TAG_SKORUPI_SHINY,
    [SPECIES_DRAPION] = OBJ_EVENT_PAL_TAG_DRAPION_SHINY,
    [SPECIES_CROAGUNK] = OBJ_EVENT_PAL_TAG_CROAGUNK_SHINY,
    [SPECIES_TOXICROAK] = OBJ_EVENT_PAL_TAG_TOXICROAK_SHINY,
    [SPECIES_CARNIVINE] = OBJ_EVENT_PAL_TAG_CARNIVINE_SHINY,
    [SPECIES_FINNEON] = OBJ_EVENT_PAL_TAG_FINNEON_SHINY,
    [SPECIES_LUMINEON] = OBJ_EVENT_PAL_TAG_LUMINEON_SHINY,
    [SPECIES_MANTYKE] = OBJ_EVENT_PAL_TAG_MANTYKE_SHINY,
    [SPECIES_SNOVER] = OBJ_EVENT_PAL_TAG_SNOVER_SHINY,
    [SPECIES_ABOMASNOW] = OBJ_EVENT_PAL_TAG_ABOMASNOW_SHINY,
    [SPECIES_WEAVILE] = OBJ_EVENT_PAL_TAG_WEAVILE_SHINY,
    [SPECIES_MAGNEZONE] = OBJ_EVENT_PAL_TAG_MAGNEZONE_SHINY,
    [SPECIES_LICKILICKY] = OBJ_EVENT_PAL_TAG_LICKILICKY_SHINY,
    [SPECIES_RHYPERIOR] = OBJ_EVENT_PAL_TAG_RHYPERIOR_SHINY,
    [SPECIES_TANGROWTH] = OBJ_EVENT_PAL_TAG_TANGROWTH_SHINY,
    [SPECIES_ELECTIVIRE] = OBJ_EVENT_PAL_TAG_ELECTIVIRE_SHINY,
    [SPECIES_MAGMORTAR] = OBJ_EVENT_PAL_TAG_MAGMORTAR_SHINY,
    [SPECIES_TOGEKISS] = OBJ_EVENT_PAL_TAG_TOGEKISS_SHINY,
    [SPECIES_YANMEGA] = OBJ_EVENT_PAL_TAG_YANMEGA_SHINY,
    [SPECIES_LEAFEON] = OBJ_EVENT_PAL_TAG_LEAFEON_SHINY,
    [SPECIES_GLACEON] = OBJ_EVENT_PAL_TAG_GLACEON_SHINY,
    [SPECIES_GLISCOR] = OBJ_EVENT_PAL_TAG_GLISCOR_SHINY,
    [SPECIES_MAMOSWINE] = OBJ_EVENT_PAL_TAG_MAMOSWINE_SHINY,
    [SPECIES_PORYGON_Z] = OBJ_EVENT_PAL_TAG_PORYGON_Z_SHINY,
    [SPECIES_GALLADE] = OBJ_EVENT_PAL_TAG_GALLADE_SHINY,
    [SPECIES_PROBOPASS] = OBJ_EVENT_PAL_TAG_PROBOPASS_SHINY,
    [SPECIES_DUSKNOIR] = OBJ_EVENT_PAL_TAG_DUSKNOIR_SHINY,
    [SPECIES_FROSLASS] = OBJ_EVENT_PAL_TAG_FROSLASS_SHINY,
    [SPECIES_ROTOM] = OBJ_EVENT_PAL_TAG_ROTOM_SHINY,
    [SPECIES_UXIE] = OBJ_EVENT_PAL_TAG_UXIE_SHINY,
    [SPECIES_MESPRIT] = OBJ_EVENT_PAL_TAG_MESPRIT_SHINY,
    [SPECIES_AZELF] = OBJ_EVENT_PAL_TAG_AZELF_SHINY,
    [SPECIES_DIALGA] = OBJ_EVENT_PAL_TAG_DIALGA_SHINY,
    [SPECIES_PALKIA] = OBJ_EVENT_PAL_TAG_PALKIA_SHINY,
    [SPECIES_HEATRAN] = OBJ_EVENT_PAL_TAG_HEATRAN_SHINY,
    [SPECIES_REGIGIGAS] = OBJ_EVENT_PAL_TAG_REGIGIGAS_SHINY,
    [SPECIES_GIRATINA] = OBJ_EVENT_PAL_TAG_GIRATINA_SHINY,
    [SPECIES_CRESSELIA] = OBJ_EVENT_PAL_TAG_CRESSELIA_SHINY,
    [SPECIES_PHIONE] = OBJ_EVENT_PAL_TAG_PHIONE_SHINY,
    [SPECIES_MANAPHY] = OBJ_EVENT_PAL_TAG_MANAPHY_SHINY,
    [SPECIES_DARKRAI] = OBJ_EVENT_PAL_TAG_DARKRAI_SHINY,
    [SPECIES_SHAYMIN] = OBJ_EVENT_PAL_TAG_SHAYMIN_SHINY,
    [SPECIES_ARCEUS] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_VICTINI] = OBJ_EVENT_PAL_TAG_VICTINI_SHINY,
    [SPECIES_SNIVY] = OBJ_EVENT_PAL_TAG_SNIVY_SHINY,
    [SPECIES_SERVINE] = OBJ_EVENT_PAL_TAG_SERVINE_SHINY,
    [SPECIES_SERPERIOR] = OBJ_EVENT_PAL_TAG_SERPERIOR_SHINY,
    [SPECIES_TEPIG] = OBJ_EVENT_PAL_TAG_TEPIG_SHINY,
    [SPECIES_PIGNITE] = OBJ_EVENT_PAL_TAG_PIGNITE_SHINY,
    [SPECIES_EMBOAR] = OBJ_EVENT_PAL_TAG_EMBOAR_SHINY,
    [SPECIES_OSHAWOTT] = OBJ_EVENT_PAL_TAG_OSHAWOTT_SHINY,
    [SPECIES_DEWOTT] = OBJ_EVENT_PAL_TAG_DEWOTT_SHINY,
    [SPECIES_SAMUROTT] = OBJ_EVENT_PAL_TAG_SAMUROTT_SHINY,
    [SPECIES_PATRAT] = OBJ_EVENT_PAL_TAG_PATRAT_SHINY,
    [SPECIES_WATCHOG] = OBJ_EVENT_PAL_TAG_WATCHOG_SHINY,
    [SPECIES_LILLIPUP] = OBJ_EVENT_PAL_TAG_LILLIPUP_SHINY,
    [SPECIES_HERDIER] = OBJ_EVENT_PAL_TAG_HERDIER_SHINY,
    [SPECIES_STOUTLAND] = OBJ_EVENT_PAL_TAG_STOUTLAND_SHINY,
    [SPECIES_PURRLOIN] = OBJ_EVENT_PAL_TAG_PURRLOIN_SHINY,
    [SPECIES_LIEPARD] = OBJ_EVENT_PAL_TAG_LIEPARD_SHINY,
    [SPECIES_PANSAGE] = OBJ_EVENT_PAL_TAG_PANSAGE_SHINY,
    [SPECIES_SIMISAGE] = OBJ_EVENT_PAL_TAG_SIMISAGE_SHINY,
    [SPECIES_PANSEAR] = OBJ_EVENT_PAL_TAG_PANSEAR_SHINY,
    [SPECIES_SIMISEAR] = OBJ_EVENT_PAL_TAG_SIMISEAR_SHINY,
    [SPECIES_PANPOUR] = OBJ_EVENT_PAL_TAG_PANPOUR_SHINY,
    [SPECIES_SIMIPOUR] = OBJ_EVENT_PAL_TAG_SIMIPOUR_SHINY,
    [SPECIES_MUNNA] = OBJ_EVENT_PAL_TAG_MUNNA_SHINY,
    [SPECIES_MUSHARNA] = OBJ_EVENT_PAL_TAG_MUSHARNA_SHINY,
    [SPECIES_PIDOVE] = OBJ_EVENT_PAL_TAG_PIDOVE_SHINY,
    [SPECIES_TRANQUILL] = OBJ_EVENT_PAL_TAG_TRANQUILL_SHINY,
    [SPECIES_UNFEZANT] = OBJ_EVENT_PAL_TAG_UNFEZANT_SHINY,
    [SPECIES_BLITZLE] = OBJ_EVENT_PAL_TAG_BLITZLE_SHINY,
    [SPECIES_ZEBSTRIKA] = OBJ_EVENT_PAL_TAG_ZEBSTRIKA_SHINY,
    [SPECIES_ROGGENROLA] = OBJ_EVENT_PAL_TAG_ROGGENROLA_SHINY,
    [SPECIES_BOLDORE] = OBJ_EVENT_PAL_TAG_BOLDORE_SHINY,
    [SPECIES_GIGALITH] = OBJ_EVENT_PAL_TAG_GIGALITH_SHINY,
    [SPECIES_WOOBAT] = OBJ_EVENT_PAL_TAG_WOOBAT_SHINY,
    [SPECIES_SWOOBAT] = OBJ_EVENT_PAL_TAG_SWOOBAT_SHINY,
    [SPECIES_DRILBUR] = OBJ_EVENT_PAL_TAG_DRILBUR_SHINY,
    [SPECIES_EXCADRILL] = OBJ_EVENT_PAL_TAG_EXCADRILL_SHINY,
    [SPECIES_AUDINO] = OBJ_EVENT_PAL_TAG_AUDINO_SHINY,
    [SPECIES_TIMBURR] = OBJ_EVENT_PAL_TAG_TIMBURR_SHINY,
    [SPECIES_GURDURR] = OBJ_EVENT_PAL_TAG_GURDURR_SHINY,
    [SPECIES_CONKELDURR] = OBJ_EVENT_PAL_TAG_CONKELDURR_SHINY,
    [SPECIES_TYMPOLE] = OBJ_EVENT_PAL_TAG_TYMPOLE_SHINY,
    [SPECIES_PALPITOAD] = OBJ_EVENT_PAL_TAG_PALPITOAD_SHINY,
    [SPECIES_SEISMITOAD] = OBJ_EVENT_PAL_TAG_SEISMITOAD_SHINY,
    [SPECIES_THROH] = OBJ_EVENT_PAL_TAG_THROH_SHINY,
    [SPECIES_SAWK] = OBJ_EVENT_PAL_TAG_SAWK_SHINY,
    [SPECIES_SEWADDLE] = OBJ_EVENT_PAL_TAG_SEWADDLE_SHINY,
    [SPECIES_SWADLOON] = OBJ_EVENT_PAL_TAG_SWADLOON_SHINY,
    [SPECIES_LEAVANNY] = OBJ_EVENT_PAL_TAG_LEAVANNY_SHINY,
    [SPECIES_VENIPEDE] = OBJ_EVENT_PAL_TAG_VENIPEDE_SHINY,
    [SPECIES_WHIRLIPEDE] = OBJ_EVENT_PAL_TAG_WHIRLIPEDE_SHINY,
    [SPECIES_SCOLIPEDE] = OBJ_EVENT_PAL_TAG_SCOLIPEDE_SHINY,
    [SPECIES_COTTONEE] = OBJ_EVENT_PAL_TAG_COTTONEE_SHINY,
    [SPECIES_WHIMSICOTT] = OBJ_EVENT_PAL_TAG_WHIMSICOTT_SHINY,
    [SPECIES_PETILIL] = OBJ_EVENT_PAL_TAG_PETILIL_SHINY,
    [SPECIES_LILLIGANT] = OBJ_EVENT_PAL_TAG_LILLIGANT_SHINY,
    [SPECIES_BASCULIN_RED] = OBJ_EVENT_PAL_TAG_BASCULIN_SHINY,
    [SPECIES_SANDILE] = OBJ_EVENT_PAL_TAG_SANDILE_SHINY,
    [SPECIES_KROKOROK] = OBJ_EVENT_PAL_TAG_KROKOROK_SHINY,
    [SPECIES_KROOKODILE] = OBJ_EVENT_PAL_TAG_KROOKODILE_SHINY,
    [SPECIES_DARUMAKA] = OBJ_EVENT_PAL_TAG_DARUMAKA_SHINY,
    [SPECIES_DARMANITAN] = OBJ_EVENT_PAL_TAG_DARMANITAN_SHINY,
    [SPECIES_MARACTUS] = OBJ_EVENT_PAL_TAG_MARACTUS_SHINY,
    [SPECIES_DWEBBLE] = OBJ_EVENT_PAL_TAG_DWEBBLE_SHINY,
    [SPECIES_CRUSTLE] = OBJ_EVENT_PAL_TAG_CRUSTLE_SHINY,
    [SPECIES_SCRAGGY] = OBJ_EVENT_PAL_TAG_SCRAGGY_SHINY,
    [SPECIES_SCRAFTY] = OBJ_EVENT_PAL_TAG_SCRAFTY_SHINY,
    [SPECIES_SIGILYPH] = OBJ_EVENT_PAL_TAG_SIGILYPH_SHINY,
    [SPECIES_YAMASK] = OBJ_EVENT_PAL_TAG_YAMASK_SHINY,
    [SPECIES_COFAGRIGUS] = OBJ_EVENT_PAL_TAG_COFAGRIGUS_SHINY,
    [SPECIES_TIRTOUGA] = OBJ_EVENT_PAL_TAG_TIRTOUGA_SHINY,
    [SPECIES_CARRACOSTA] = OBJ_EVENT_PAL_TAG_CARRACOSTA_SHINY,
    [SPECIES_ARCHEN] = OBJ_EVENT_PAL_TAG_ARCHEN_SHINY,
    [SPECIES_ARCHEOPS] = OBJ_EVENT_PAL_TAG_ARCHEOPS_SHINY,
    [SPECIES_TRUBBISH] = OBJ_EVENT_PAL_TAG_TRUBBISH_SHINY,
    [SPECIES_GARBODOR] = OBJ_EVENT_PAL_TAG_GARBODOR_SHINY,
    [SPECIES_ZORUA] = OBJ_EVENT_PAL_TAG_ZORUA_SHINY,
    [SPECIES_ZOROARK] = OBJ_EVENT_PAL_TAG_ZOROARK_SHINY,
    [SPECIES_MINCCINO] = OBJ_EVENT_PAL_TAG_MINCCINO_SHINY,
    [SPECIES_CINCCINO] = OBJ_EVENT_PAL_TAG_CINCCINO_SHINY,
    [SPECIES_GOTHITA] = OBJ_EVENT_PAL_TAG_GOTHITA_SHINY,
    [SPECIES_GOTHORITA] = OBJ_EVENT_PAL_TAG_GOTHORITA_SHINY,
    [SPECIES_GOTHITELLE] = OBJ_EVENT_PAL_TAG_GOTHITELLE_SHINY,
    [SPECIES_SOLOSIS] = OBJ_EVENT_PAL_TAG_SOLOSIS_SHINY,
    [SPECIES_DUOSION] = OBJ_EVENT_PAL_TAG_DUOSION_SHINY,
    [SPECIES_REUNICLUS] = OBJ_EVENT_PAL_TAG_REUNICLUS_SHINY,
    [SPECIES_DUCKLETT] = OBJ_EVENT_PAL_TAG_DUCKLETT_SHINY,
    [SPECIES_SWANNA] = OBJ_EVENT_PAL_TAG_SWANNA_SHINY,
    [SPECIES_VANILLITE] = OBJ_EVENT_PAL_TAG_VANILLITE_SHINY,
    [SPECIES_VANILLISH] = OBJ_EVENT_PAL_TAG_VANILLISH_SHINY,
    [SPECIES_VANILLUXE] = OBJ_EVENT_PAL_TAG_VANILLUXE_SHINY,
    [SPECIES_DEERLING] = OBJ_EVENT_PAL_TAG_DEERLING_SHINY,
    [SPECIES_SAWSBUCK] = OBJ_EVENT_PAL_TAG_SAWSBUCK_SHINY,
    [SPECIES_EMOLGA] = OBJ_EVENT_PAL_TAG_EMOLGA_SHINY,
    [SPECIES_KARRABLAST] = OBJ_EVENT_PAL_TAG_KARRABLAST_SHINY,
    [SPECIES_ESCAVALIER] = OBJ_EVENT_PAL_TAG_ESCAVALIER_SHINY,
    [SPECIES_FOONGUS] = OBJ_EVENT_PAL_TAG_FOONGUS_SHINY,
    [SPECIES_AMOONGUSS] = OBJ_EVENT_PAL_TAG_AMOONGUSS_SHINY,
    [SPECIES_FRILLISH] = OBJ_EVENT_PAL_TAG_FRILLISH_SHINY,
    [SPECIES_JELLICENT] = OBJ_EVENT_PAL_TAG_JELLICENT_SHINY,
    [SPECIES_ALOMOMOLA] = OBJ_EVENT_PAL_TAG_ALOMOMOLA_SHINY,
    [SPECIES_JOLTIK] = OBJ_EVENT_PAL_TAG_JOLTIK_SHINY,
    [SPECIES_GALVANTULA] = OBJ_EVENT_PAL_TAG_GALVANTULA_SHINY,
    [SPECIES_FERROSEED] = OBJ_EVENT_PAL_TAG_FERROSEED_SHINY,
    [SPECIES_FERROTHORN] = OBJ_EVENT_PAL_TAG_FERROTHORN_SHINY,
    [SPECIES_KLINK] = OBJ_EVENT_PAL_TAG_KLINK_SHINY,
    [SPECIES_KLANG] = OBJ_EVENT_PAL_TAG_KLANG_SHINY,
    [SPECIES_KLINKLANG] = OBJ_EVENT_PAL_TAG_KLINKLANG_SHINY,
    [SPECIES_TYNAMO] = OBJ_EVENT_PAL_TAG_TYNAMO_SHINY,
    [SPECIES_EELEKTRIK] = OBJ_EVENT_PAL_TAG_EELEKTRIK_SHINY,
    [SPECIES_EELEKTROSS] = OBJ_EVENT_PAL_TAG_EELEKTROSS_SHINY,
    [SPECIES_ELGYEM] = OBJ_EVENT_PAL_TAG_ELGYEM_SHINY,
    [SPECIES_BEHEEYEM] = OBJ_EVENT_PAL_TAG_BEHEEYEM_SHINY,
    [SPECIES_LITWICK] = OBJ_EVENT_PAL_TAG_LITWICK_SHINY,
    [SPECIES_LAMPENT] = OBJ_EVENT_PAL_TAG_LAMPENT_SHINY,
    [SPECIES_CHANDELURE] = OBJ_EVENT_PAL_TAG_CHANDELURE_SHINY,
    [SPECIES_AXEW] = OBJ_EVENT_PAL_TAG_AXEW_SHINY,
    [SPECIES_FRAXURE] = OBJ_EVENT_PAL_TAG_FRAXURE_SHINY,
    [SPECIES_HAXORUS] = OBJ_EVENT_PAL_TAG_HAXORUS_SHINY,
    [SPECIES_CUBCHOO] = OBJ_EVENT_PAL_TAG_CUBCHOO_SHINY,
    [SPECIES_BEARTIC] = OBJ_EVENT_PAL_TAG_BEARTIC_SHINY,
    [SPECIES_CRYOGONAL] = OBJ_EVENT_PAL_TAG_CRYOGONAL_SHINY,
    [SPECIES_SHELMET] = OBJ_EVENT_PAL_TAG_SHELMET_SHINY,
    [SPECIES_ACCELGOR] = OBJ_EVENT_PAL_TAG_ACCELGOR_SHINY,
    [SPECIES_STUNFISK] = OBJ_EVENT_PAL_TAG_STUNFISK_SHINY,
    [SPECIES_MIENFOO] = OBJ_EVENT_PAL_TAG_MIENFOO_SHINY,
    [SPECIES_MIENSHAO] = OBJ_EVENT_PAL_TAG_MIENSHAO_SHINY,
    [SPECIES_DRUDDIGON] = OBJ_EVENT_PAL_TAG_DRUDDIGON_SHINY,
    [SPECIES_GOLETT] = OBJ_EVENT_PAL_TAG_GOLETT_SHINY,
    [SPECIES_GOLURK] = OBJ_EVENT_PAL_TAG_GOLURK_SHINY,
    [SPECIES_PAWNIARD] = OBJ_EVENT_PAL_TAG_PAWNIARD_SHINY,
    [SPECIES_BISHARP] = OBJ_EVENT_PAL_TAG_BISHARP_SHINY,
    [SPECIES_BOUFFALANT] = OBJ_EVENT_PAL_TAG_BOUFFALANT_SHINY,
    [SPECIES_RUFFLET] = OBJ_EVENT_PAL_TAG_RUFFLET_SHINY,
    [SPECIES_BRAVIARY] = OBJ_EVENT_PAL_TAG_BRAVIARY_SHINY,
    [SPECIES_VULLABY] = OBJ_EVENT_PAL_TAG_VULLABY_SHINY,
    [SPECIES_MANDIBUZZ] = OBJ_EVENT_PAL_TAG_MANDIBUZZ_SHINY,
    [SPECIES_HEATMOR] = OBJ_EVENT_PAL_TAG_HEATMOR_SHINY,
    [SPECIES_DURANT] = OBJ_EVENT_PAL_TAG_DURANT_SHINY,
    [SPECIES_DEINO] = OBJ_EVENT_PAL_TAG_DEINO_SHINY,
    [SPECIES_ZWEILOUS] = OBJ_EVENT_PAL_TAG_ZWEILOUS_SHINY,
    [SPECIES_HYDREIGON] = OBJ_EVENT_PAL_TAG_HYDREIGON_SHINY,
    [SPECIES_LARVESTA] = OBJ_EVENT_PAL_TAG_LARVESTA_SHINY,
    [SPECIES_VOLCARONA] = OBJ_EVENT_PAL_TAG_VOLCARONA_SHINY,
    [SPECIES_COBALION] = OBJ_EVENT_PAL_TAG_COBALION_SHINY,
    [SPECIES_TERRAKION] = OBJ_EVENT_PAL_TAG_TERRAKION_SHINY,
    [SPECIES_VIRIZION] = OBJ_EVENT_PAL_TAG_VIRIZION_SHINY,
    [SPECIES_TORNADUS] = OBJ_EVENT_PAL_TAG_TORNADUS_SHINY,
    [SPECIES_THUNDURUS] = OBJ_EVENT_PAL_TAG_THUNDURUS_SHINY,
    [SPECIES_RESHIRAM] = OBJ_EVENT_PAL_TAG_RESHIRAM_SHINY,
    [SPECIES_ZEKROM] = OBJ_EVENT_PAL_TAG_ZEKROM_SHINY,
    [SPECIES_LANDORUS] = OBJ_EVENT_PAL_TAG_LANDORUS_SHINY,
    [SPECIES_KYUREM] = OBJ_EVENT_PAL_TAG_KYUREM_SHINY,
    [SPECIES_KELDEO] = OBJ_EVENT_PAL_TAG_KELDEO_SHINY,
    [SPECIES_MELOETTA] = OBJ_EVENT_PAL_TAG_MELOETTA_SHINY,
    [SPECIES_GENESECT] = OBJ_EVENT_PAL_TAG_GENESECT_SHINY,
    [SPECIES_UNFEZANT_F] = OBJ_EVENT_PAL_TAG_UNFEZANT_F_SHINY,
    [SPECIES_FRILLISH_F] = OBJ_EVENT_PAL_TAG_FRILLISH_F_SHINY,
    [SPECIES_JELLICENT_F] = OBJ_EVENT_PAL_TAG_JELLICENT_F_SHINY,
    [SPECIES_BURMY_SANDY] = OBJ_EVENT_PAL_TAG_BURMY_SHINY,
    [SPECIES_BURMY_TRASH] = OBJ_EVENT_PAL_TAG_BURMY_SHINY,
    [SPECIES_WORMADAM_SANDY] = OBJ_EVENT_PAL_TAG_WORMADAM_SHINY,
    [SPECIES_WORMADAM_TRASH] = OBJ_EVENT_PAL_TAG_WORMADAM_SHINY,
    [SPECIES_SHELLOS_EAST] = OBJ_EVENT_PAL_TAG_SHELLOS_E_SHINY,
    [SPECIES_GASTRODON_EAST] = OBJ_EVENT_PAL_TAG_GASTRODON_E_SHINY,
    [SPECIES_ROTOM_HEAT] = OBJ_EVENT_PAL_TAG_ROTOM_H_SHINY,
    [SPECIES_ROTOM_WASH] = OBJ_EVENT_PAL_TAG_ROTOM_W_SHINY,
    [SPECIES_ROTOM_FROST] = OBJ_EVENT_PAL_TAG_ROTOM_FR_SHINY,
    [SPECIES_ROTOM_FAN] = OBJ_EVENT_PAL_TAG_ROTOM_F_SHINY,
    [SPECIES_ROTOM_MOW] = OBJ_EVENT_PAL_TAG_ROTOM_M_SHINY,
    [SPECIES_GIRATINA_ORIGIN] = OBJ_EVENT_PAL_TAG_GIRATINA_O_SHINY,
    [SPECIES_SHAYMIN_SKY] = OBJ_EVENT_PAL_TAG_SHAYMIN_S_SHINY,
    [SPECIES_ARCEUS_FIGHT] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_FLYING] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_POISON] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_GROUND] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_ROCK] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_BUG] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_GHOST] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_STEEL] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_FIRE] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_WATER] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_GRASS] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_ELECTRIC] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_PSYCHIC] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_ICE] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_DRAGON] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ARCEUS_DARK] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_BASCULIN_BLUE] = OBJ_EVENT_PAL_TAG_BASCULIN_B_SHINY,
    [SPECIES_DEERLING_SUMMER] = OBJ_EVENT_PAL_TAG_DEERLING_SHINY,
    [SPECIES_DEERLING_AUTUMN] = OBJ_EVENT_PAL_TAG_DEERLING_SHINY,
    [SPECIES_DEERLING_WINTER] = OBJ_EVENT_PAL_TAG_DEERLING_SHINY,
    [SPECIES_SAWSBUCK_SUMMER] = OBJ_EVENT_PAL_TAG_SAWSBUCK_SHINY,
    [SPECIES_SAWSBUCK_AUTUMN] = OBJ_EVENT_PAL_TAG_SAWSBUCK_SHINY,
    [SPECIES_SAWSBUCK_WINTER] = OBJ_EVENT_PAL_TAG_SAWSBUCK_SHINY,
    [SPECIES_HIPPOPOTAS_F] = OBJ_EVENT_PAL_TAG_HIPPOPOTAS_SHINY,
    [SPECIES_HIPPOWDON_F] = OBJ_EVENT_PAL_TAG_HIPPOWDON_SHINY,
    [SPECIES_MELOETTA_PIROUETTE] = OBJ_EVENT_PAL_TAG_MELOETTA_P_SHINY,
    [SPECIES_GENESECT_SHOCK] = OBJ_EVENT_PAL_TAG_GENESECT_SHINY,
    [SPECIES_GENESECT_BURN] = OBJ_EVENT_PAL_TAG_GENESECT_SHINY,
    [SPECIES_GENESECT_CHILL] = OBJ_EVENT_PAL_TAG_GENESECT_SHINY,
    [SPECIES_GENESECT_DOUSE] = OBJ_EVENT_PAL_TAG_GENESECT_SHINY,
    [SPECIES_KYUREM_BLACK] = OBJ_EVENT_PAL_TAG_KYUREM_B_SHINY,
    [SPECIES_KYUREM_WHITE] = OBJ_EVENT_PAL_TAG_KYUREM_W_SHINY,
    [SPECIES_TORNADUS_THERIAN] = OBJ_EVENT_PAL_TAG_TORNADUS_T_SHINY,
    [SPECIES_THUNDURUS_THERIAN] = OBJ_EVENT_PAL_TAG_THUNDURUS_T_SHINY,
    [SPECIES_LANDORUS_THERIAN] = OBJ_EVENT_PAL_TAG_LANDORUS_T_SHINY,
    [SPECIES_KELDEO_RESOLUTE] = OBJ_EVENT_PAL_TAG_KELDEO_SHINY,
    [SPECIES_CHESPIN] = OBJ_EVENT_PAL_TAG_CHESPIN_SHINY,
    [SPECIES_QUILLADIN] = OBJ_EVENT_PAL_TAG_QUILLADIN_SHINY,
    [SPECIES_CHESNAUGHT] = OBJ_EVENT_PAL_TAG_CHESNAUGHT_SHINY,
    [SPECIES_FENNEKIN] = OBJ_EVENT_PAL_TAG_FENNEKIN_SHINY,
    [SPECIES_BRAIXEN] = OBJ_EVENT_PAL_TAG_BRAIXEN_SHINY,
    [SPECIES_DELPHOX] = OBJ_EVENT_PAL_TAG_DELPHOX_SHINY,
    [SPECIES_FROAKIE] = OBJ_EVENT_PAL_TAG_FROAKIE_SHINY,
    [SPECIES_FROGADIER] = OBJ_EVENT_PAL_TAG_FROGADIER_SHINY,
    [SPECIES_GRENINJA] = OBJ_EVENT_PAL_TAG_GRENINJA_SHINY,
    [SPECIES_BUNNELBY] = OBJ_EVENT_PAL_TAG_BUNNELBY_SHINY,
    [SPECIES_DIGGERSBY] = OBJ_EVENT_PAL_TAG_DIGGERSBY_SHINY,
    [SPECIES_FLETCHLING] = OBJ_EVENT_PAL_TAG_FLETCHLING_SHINY,
    [SPECIES_FLETCHINDER] = OBJ_EVENT_PAL_TAG_FLETCHINDER_SHINY,
    [SPECIES_TALONFLAME] = OBJ_EVENT_PAL_TAG_TALONFLAME_SHINY,
    [SPECIES_SCATTERBUG] = OBJ_EVENT_PAL_TAG_SCATTERBUG_SHINY,
    [SPECIES_SPEWPA] = OBJ_EVENT_PAL_TAG_SPEWPA_SHINY,
    [SPECIES_VIVILLON] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_LITLEO] = OBJ_EVENT_PAL_TAG_LITLEO_SHINY,
    [SPECIES_PYROAR] = OBJ_EVENT_PAL_TAG_PYROAR_SHINY,
    [SPECIES_FLABEBE] = OBJ_EVENT_PAL_TAG_FLABEBE_SHINY,
    [SPECIES_FLOETTE] = OBJ_EVENT_PAL_TAG_FLOETTE_SHINY,
    [SPECIES_FLORGES] = OBJ_EVENT_PAL_TAG_FLORGES_SHINY,
    [SPECIES_SKIDDO] = OBJ_EVENT_PAL_TAG_SKIDDO_SHINY,
    [SPECIES_GOGOAT] = OBJ_EVENT_PAL_TAG_GOGOAT_SHINY,
    [SPECIES_PANCHAM] = OBJ_EVENT_PAL_TAG_PANCHAM_SHINY,
    [SPECIES_PANGORO] = OBJ_EVENT_PAL_TAG_PANGORO_SHINY,
    [SPECIES_FURFROU] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_ESPURR] = OBJ_EVENT_PAL_TAG_ESPURR_SHINY,
    [SPECIES_MEOWSTIC] = OBJ_EVENT_PAL_TAG_MEOWSTIC_SHINY,
    [SPECIES_HONEDGE] = OBJ_EVENT_PAL_TAG_HONEDGE_SHINY,
    [SPECIES_DOUBLADE] = OBJ_EVENT_PAL_TAG_DOUBLADE_SHINY,
    [SPECIES_AEGISLASH] = OBJ_EVENT_PAL_TAG_AEGISLASH_SHINY,
    [SPECIES_SPRITZEE] = OBJ_EVENT_PAL_TAG_SPRITZEE_SHINY,
    [SPECIES_AROMATISSE] = OBJ_EVENT_PAL_TAG_AROMATISSE_SHINY,
    [SPECIES_SWIRLIX] = OBJ_EVENT_PAL_TAG_SWIRLIX_SHINY,
    [SPECIES_SLURPUFF] = OBJ_EVENT_PAL_TAG_SLURPUFF_SHINY,
    [SPECIES_INKAY] = OBJ_EVENT_PAL_TAG_INKAY_SHINY,
    [SPECIES_MALAMAR] = OBJ_EVENT_PAL_TAG_MALAMAR_SHINY,
    [SPECIES_BINACLE] = OBJ_EVENT_PAL_TAG_BINACLE_SHINY,
    [SPECIES_BARBARACLE] = OBJ_EVENT_PAL_TAG_BARBARACLE_SHINY,
    [SPECIES_SKRELP] = OBJ_EVENT_PAL_TAG_SKRELP_SHINY,
    [SPECIES_DRAGALGE] = OBJ_EVENT_PAL_TAG_DRAGALGE_SHINY,
    [SPECIES_CLAUNCHER] = OBJ_EVENT_PAL_TAG_CLAUNCHER_SHINY,
    [SPECIES_CLAWITZER] = OBJ_EVENT_PAL_TAG_CLAWITZER_SHINY,
    [SPECIES_HELIOPTILE] = OBJ_EVENT_PAL_TAG_HELIOPTILE_SHINY,
    [SPECIES_HELIOLISK] = OBJ_EVENT_PAL_TAG_HELIOLISK_SHINY,
    [SPECIES_TYRUNT] = OBJ_EVENT_PAL_TAG_TYRUNT_SHINY,
    [SPECIES_TYRANTRUM] = OBJ_EVENT_PAL_TAG_TYRANTRUM_SHINY,
    [SPECIES_AMAURA] = OBJ_EVENT_PAL_TAG_AMAURA_SHINY,
    [SPECIES_AURORUS] = OBJ_EVENT_PAL_TAG_AURORUS_SHINY,
    [SPECIES_SYLVEON] = OBJ_EVENT_PAL_TAG_SYLVEON_SHINY,
    [SPECIES_HAWLUCHA] = OBJ_EVENT_PAL_TAG_HAWLUCHA_SHINY,
    [SPECIES_DEDENNE] = OBJ_EVENT_PAL_TAG_DEDENNE_SHINY,
    [SPECIES_CARBINK] = OBJ_EVENT_PAL_TAG_CARBINK_SHINY,
    [SPECIES_GOOMY] = OBJ_EVENT_PAL_TAG_GOOMY_SHINY,
    [SPECIES_SLIGGOO] = OBJ_EVENT_PAL_TAG_SLIGGOO_SHINY,
    [SPECIES_GOODRA] = OBJ_EVENT_PAL_TAG_GOODRA_SHINY,
    [SPECIES_KLEFKI] = OBJ_EVENT_PAL_TAG_KLEFKI_SHINY,
    [SPECIES_PHANTUMP] = OBJ_EVENT_PAL_TAG_PHANTUMP_SHINY,
    [SPECIES_TREVENANT] = OBJ_EVENT_PAL_TAG_TREVENANT_SHINY,
    [SPECIES_PUMPKABOO] = OBJ_EVENT_PAL_TAG_PUMPKABOO_SHINY,
    [SPECIES_GOURGEIST] = OBJ_EVENT_PAL_TAG_GOURGEIST_SHINY,
    [SPECIES_BERGMITE] = OBJ_EVENT_PAL_TAG_BERGMITE_SHINY,
    [SPECIES_AVALUGG] = OBJ_EVENT_PAL_TAG_AVALUGG_SHINY,
    [SPECIES_NOIBAT] = OBJ_EVENT_PAL_TAG_NOIBAT_SHINY,
    [SPECIES_NOIVERN] = OBJ_EVENT_PAL_TAG_NOIVERN_SHINY,
    [SPECIES_XERNEAS] = OBJ_EVENT_PAL_TAG_XERNEAS_SHINY,
    [SPECIES_YVELTAL] = OBJ_EVENT_PAL_TAG_YVELTAL_SHINY,
    [SPECIES_ZYGARDE] = OBJ_EVENT_PAL_TAG_ZYGARDE_SHINY,
    [SPECIES_DIANCIE] = OBJ_EVENT_PAL_TAG_DIANCIE_SHINY,
    [SPECIES_HOOPA] = OBJ_EVENT_PAL_TAG_HOOPA_SHINY,
    [SPECIES_HOOPA_UNBOUND] = OBJ_EVENT_PAL_TAG_HOOPA_U_SHINY,
    [SPECIES_VOLCANION] = OBJ_EVENT_PAL_TAG_VOLCANION_SHINY,
    [SPECIES_PYROAR_FEMALE] = OBJ_EVENT_PAL_TAG_PYROAR_F_SHINY,
    [SPECIES_MEOWSTIC_FEMALE] = OBJ_EVENT_PAL_TAG_MEOWSTIC_F_SHINY,
    [SPECIES_ARCEUS_FAIRY] = OBJ_EVENT_PAL_TAG_ARCEUS_SHINY,
    [SPECIES_ZYGARDE_10] = OBJ_EVENT_PAL_TAG_ZYGARDE_10_SHINY,
    [SPECIES_FLABEBE_BLUE] = OBJ_EVENT_PAL_TAG_FLABEBE_SHINY,
    [SPECIES_FLABEBE_ORANGE] = OBJ_EVENT_PAL_TAG_FLABEBE_SHINY,
    [SPECIES_FLABEBE_YELLOW] = OBJ_EVENT_PAL_TAG_FLABEBE_SHINY,
    [SPECIES_FLABEBE_WHITE] = OBJ_EVENT_PAL_TAG_FLABEBE_SHINY,
    [SPECIES_FLOETTE_BLUE] = OBJ_EVENT_PAL_TAG_FLOETTE_SHINY,
    [SPECIES_FLOETTE_ORANGE] = OBJ_EVENT_PAL_TAG_FLOETTE_SHINY,
    [SPECIES_FLOETTE_YELLOW] = OBJ_EVENT_PAL_TAG_FLOETTE_SHINY,
    [SPECIES_FLOETTE_WHITE] = OBJ_EVENT_PAL_TAG_FLOETTE_SHINY,
    [SPECIES_FLOETTE_ETERNAL] = OBJ_EVENT_PAL_TAG_FLOETTE_E_SHINY,
    [SPECIES_FLORGES_BLUE] = OBJ_EVENT_PAL_TAG_FLORGES_SHINY,
    [SPECIES_FLORGES_ORANGE] = OBJ_EVENT_PAL_TAG_FLORGES_SHINY,
    [SPECIES_FLORGES_YELLOW] = OBJ_EVENT_PAL_TAG_FLORGES_SHINY,
    [SPECIES_FLORGES_WHITE] = OBJ_EVENT_PAL_TAG_FLORGES_SHINY,
    [SPECIES_PUMPKABOO_XL] = OBJ_EVENT_PAL_TAG_PUMPKABOO_SHINY,
    [SPECIES_PUMPKABOO_L] = OBJ_EVENT_PAL_TAG_PUMPKABOO_SHINY,
    [SPECIES_PUMPKABOO_M] = OBJ_EVENT_PAL_TAG_PUMPKABOO_SHINY,
    [SPECIES_GOURGEIST_XL] = OBJ_EVENT_PAL_TAG_GOURGEIST_SHINY,
    [SPECIES_GOURGEIST_L] = OBJ_EVENT_PAL_TAG_GOURGEIST_SHINY,
    [SPECIES_GOURGEIST_M] = OBJ_EVENT_PAL_TAG_GOURGEIST_SHINY,
    [SPECIES_FURFROU_HEART] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_DIAMOND] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_STAR] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_PHAROAH] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_KABUKI] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_LA_REINE] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_MATRON] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_DANDY] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_FURFROU_DEBUTANTE] = OBJ_EVENT_PAL_TAG_FURFROU_SHINY,
    [SPECIES_VIVILLON_FANCY] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_ARCHIPELAGO] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_CONTINENTAL] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_ELEGANT] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_GARDEN] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_HIGH_PLAINS] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_ICY_SNOW] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_JUNGLE] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_MARINE] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_MODERN] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_MONSOON] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_OCEAN] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_POKEBALL] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_POLAR] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_RIVER] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_SANDSTORM] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_SAVANNA] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_SUN] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_VIVILLON_TUNDRA] = OBJ_EVENT_PAL_TAG_VIVILLON_SHINY,
    [SPECIES_ROWLET] = OBJ_EVENT_PAL_TAG_ROWLET_SHINY,
    [SPECIES_DARTRIX] = OBJ_EVENT_PAL_TAG_DARTRIX_SHINY,
    [SPECIES_DECIDUEYE] = OBJ_EVENT_PAL_TAG_DECIDUEYE_SHINY,
    [SPECIES_LITTEN] = OBJ_EVENT_PAL_TAG_LITTEN_SHINY,
    [SPECIES_TORRACAT] = OBJ_EVENT_PAL_TAG_TORRACAT_SHINY,
    [SPECIES_INCINEROAR] = OBJ_EVENT_PAL_TAG_INCINEROAR_SHINY,
    [SPECIES_POPPLIO] = OBJ_EVENT_PAL_TAG_POPPLIO_SHINY,
    [SPECIES_BRIONNE] = OBJ_EVENT_PAL_TAG_BRIONNE_SHINY,
    [SPECIES_PRIMARINA] = OBJ_EVENT_PAL_TAG_PRIMARINA_SHINY,
    [SPECIES_PIKIPEK] = OBJ_EVENT_PAL_TAG_PIKIPEK_SHINY,
    [SPECIES_TRUMBEAK] = OBJ_EVENT_PAL_TAG_TRUMBEAK_SHINY,
    [SPECIES_TOUCANNON] = OBJ_EVENT_PAL_TAG_TOUCANNON_SHINY,
    [SPECIES_YUNGOOS] = OBJ_EVENT_PAL_TAG_YUNGOOS_SHINY,
    [SPECIES_GUMSHOOS] = OBJ_EVENT_PAL_TAG_GUMSHOOS_SHINY,
    [SPECIES_GRUBBIN] = OBJ_EVENT_PAL_TAG_GRUBBIN_SHINY,
    [SPECIES_CHARJABUG] = OBJ_EVENT_PAL_TAG_CHARJABUG_SHINY,
    [SPECIES_VIKAVOLT] = OBJ_EVENT_PAL_TAG_VIKAVOLT_SHINY,
    [SPECIES_CRABRAWLER] = OBJ_EVENT_PAL_TAG_CRABRAWLER_SHINY,
    [SPECIES_CRABOMINABLE] = OBJ_EVENT_PAL_TAG_CRABOMINABLE_SHINY,
    [SPECIES_ORICORIO] = OBJ_EVENT_PAL_TAG_ORICORIO_SHINY,
    [SPECIES_CUTIEFLY] = OBJ_EVENT_PAL_TAG_CUTIEFLY_SHINY,
    [SPECIES_RIBOMBEE] = OBJ_EVENT_PAL_TAG_RIBOMBEE_SHINY,
    [SPECIES_ROCKRUFF] = OBJ_EVENT_PAL_TAG_ROCKRUFF_SHINY,
    [SPECIES_LYCANROC] = OBJ_EVENT_PAL_TAG_LYCANROC_SHINY,
    [SPECIES_WISHIWASHI] = OBJ_EVENT_PAL_TAG_WISHIWASHI_SHINY,
    [SPECIES_MAREANIE] = OBJ_EVENT_PAL_TAG_MAREANIE_SHINY,
    [SPECIES_TOXAPEX] = OBJ_EVENT_PAL_TAG_TOXAPEX_SHINY,
    [SPECIES_MUDBRAY] = OBJ_EVENT_PAL_TAG_MUDBRAY_SHINY,
    [SPECIES_MUDSDALE] = OBJ_EVENT_PAL_TAG_MUDSDALE_SHINY,
    [SPECIES_DEWPIDER] = OBJ_EVENT_PAL_TAG_DEWPIDER_SHINY,
    [SPECIES_ARAQUANID] = OBJ_EVENT_PAL_TAG_ARAQUANID_SHINY,
    [SPECIES_FOMANTIS] = OBJ_EVENT_PAL_TAG_FOMANTIS_SHINY,
    [SPECIES_LURANTIS] = OBJ_EVENT_PAL_TAG_LURANTIS_SHINY,
    [SPECIES_MORELULL] = OBJ_EVENT_PAL_TAG_MORELULL_SHINY,
    [SPECIES_SHIINOTIC] = OBJ_EVENT_PAL_TAG_SHIINOTIC_SHINY,
    [SPECIES_SALANDIT] = OBJ_EVENT_PAL_TAG_SALANDIT_SHINY,
    [SPECIES_SALAZZLE] = OBJ_EVENT_PAL_TAG_SALAZZLE_SHINY,
    [SPECIES_STUFFUL] = OBJ_EVENT_PAL_TAG_STUFFUL_SHINY,
    [SPECIES_BEWEAR] = OBJ_EVENT_PAL_TAG_BEWEAR_SHINY,
    [SPECIES_BOUNSWEET] = OBJ_EVENT_PAL_TAG_BOUNSWEET_SHINY,
    [SPECIES_STEENEE] = OBJ_EVENT_PAL_TAG_STEENEE_SHINY,
    [SPECIES_TSAREENA] = OBJ_EVENT_PAL_TAG_TSAREENA_SHINY,
    [SPECIES_COMFEY] = OBJ_EVENT_PAL_TAG_COMFEY_SHINY,
    [SPECIES_ORANGURU] = OBJ_EVENT_PAL_TAG_ORANGURU_SHINY,
    [SPECIES_PASSIMIAN] = OBJ_EVENT_PAL_TAG_PASSIMIAN_SHINY,
    [SPECIES_WIMPOD] = OBJ_EVENT_PAL_TAG_WIMPOD_SHINY,
    [SPECIES_GOLISOPOD] = OBJ_EVENT_PAL_TAG_GOLISOPOD_SHINY,
    [SPECIES_SANDYGAST] = OBJ_EVENT_PAL_TAG_SANDYGAST_SHINY,
    [SPECIES_PALOSSAND] = OBJ_EVENT_PAL_TAG_PALOSSAND_SHINY,
    [SPECIES_PYUKUMUKU] = OBJ_EVENT_PAL_TAG_PYUKUMUKU_SHINY,
    [SPECIES_TYPE_NULL] = OBJ_EVENT_PAL_TAG_TYPE_NULL_SHINY,
    [SPECIES_SILVALLY] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_MINIOR_SHIELD] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_KOMALA] = OBJ_EVENT_PAL_TAG_KOMALA_SHINY,
    [SPECIES_TURTONATOR] = OBJ_EVENT_PAL_TAG_TURTONATOR_SHINY,
    [SPECIES_TOGEDEMARU] = OBJ_EVENT_PAL_TAG_TOGEDEMARU_SHINY,
    [SPECIES_MIMIKYU] = OBJ_EVENT_PAL_TAG_MIMIKYU_SHINY,
    [SPECIES_BRUXISH] = OBJ_EVENT_PAL_TAG_BRUXISH_SHINY,
    [SPECIES_DRAMPA] = OBJ_EVENT_PAL_TAG_DRAMPA_SHINY,
    [SPECIES_DHELMISE] = OBJ_EVENT_PAL_TAG_DHELMISE_SHINY,
    [SPECIES_JANGMO_O] = OBJ_EVENT_PAL_TAG_JANGMO_O_SHINY,
    [SPECIES_HAKAMO_O] = OBJ_EVENT_PAL_TAG_HAKAMO_O_SHINY,
    [SPECIES_KOMMO_O] = OBJ_EVENT_PAL_TAG_KOMMO_O_SHINY,
    [SPECIES_TAPU_KOKO] = OBJ_EVENT_PAL_TAG_TAPU_KOKO_SHINY,
    [SPECIES_TAPU_LELE] = OBJ_EVENT_PAL_TAG_TAPU_LELE_SHINY,
    [SPECIES_TAPU_BULU] = OBJ_EVENT_PAL_TAG_TAPU_BULU_SHINY,
    [SPECIES_TAPU_FINI] = OBJ_EVENT_PAL_TAG_TAPU_FINI_SHINY,
    [SPECIES_COSMOG] = OBJ_EVENT_PAL_TAG_COSMOG_SHINY,
    [SPECIES_COSMOEM] = OBJ_EVENT_PAL_TAG_COSMOEM_SHINY,
    [SPECIES_SOLGALEO] = OBJ_EVENT_PAL_TAG_SOLGALEO_SHINY,
    [SPECIES_LUNALA] = OBJ_EVENT_PAL_TAG_LUNALA_SHINY,
    [SPECIES_NIHILEGO] = OBJ_EVENT_PAL_TAG_NIHILEGO_SHINY,
    [SPECIES_BUZZWOLE] = OBJ_EVENT_PAL_TAG_BUZZWOLE_SHINY,
    [SPECIES_PHEROMOSA] = OBJ_EVENT_PAL_TAG_PHEROMOSA_SHINY,
    [SPECIES_XURKITREE] = OBJ_EVENT_PAL_TAG_XURKITREE_SHINY,
    [SPECIES_CELESTEELA] = OBJ_EVENT_PAL_TAG_CELESTEELA_SHINY,
    [SPECIES_KARTANA] = OBJ_EVENT_PAL_TAG_KARTANA_SHINY,
    [SPECIES_GUZZLORD] = OBJ_EVENT_PAL_TAG_GUZZLORD_SHINY,
    [SPECIES_NECROZMA] = OBJ_EVENT_PAL_TAG_NECROZMA_SHINY,
    [SPECIES_MAGEARNA] = OBJ_EVENT_PAL_TAG_MAGEARNA_SHINY,
    [SPECIES_MARSHADOW] = OBJ_EVENT_PAL_TAG_MARSHADOW_SHINY,
    [SPECIES_RATTATA_A] = OBJ_EVENT_PAL_TAG_RATTATA_A_SHINY,
    [SPECIES_RATICATE_A] = OBJ_EVENT_PAL_TAG_RATICATE_A_SHINY,
    [SPECIES_RAICHU_A] = OBJ_EVENT_PAL_TAG_RAICHU_A_SHINY,
    [SPECIES_SANDSHREW_A] = OBJ_EVENT_PAL_TAG_SANDSHREW_A_SHINY,
    [SPECIES_SANDSLASH_A] = OBJ_EVENT_PAL_TAG_SANDSLASH_A_SHINY,
    [SPECIES_VULPIX_A] = OBJ_EVENT_PAL_TAG_VULPIX_A_SHINY,
    [SPECIES_NINETALES_A] = OBJ_EVENT_PAL_TAG_NINETALES_A_SHINY,
    [SPECIES_DIGLETT_A] = OBJ_EVENT_PAL_TAG_DIGLETT_A_SHINY,
    [SPECIES_DUGTRIO_A] = OBJ_EVENT_PAL_TAG_DUGTRIO_A_SHINY,
    [SPECIES_MEOWTH_A] = OBJ_EVENT_PAL_TAG_MEOWTH_A_SHINY,
    [SPECIES_PERSIAN_A] = OBJ_EVENT_PAL_TAG_PERSIAN_A_SHINY,
    [SPECIES_GEODUDE_A] = OBJ_EVENT_PAL_TAG_GEODUDE_A_SHINY,
    [SPECIES_GRAVELER_A] = OBJ_EVENT_PAL_TAG_GRAVELER_A_SHINY,
    [SPECIES_GOLEM_A] = OBJ_EVENT_PAL_TAG_GOLEM_A_SHINY,
    [SPECIES_GRIMER_A] = OBJ_EVENT_PAL_TAG_GRIMER_A_SHINY,
    [SPECIES_MUK_A] = OBJ_EVENT_PAL_TAG_MUK_A_SHINY,
    [SPECIES_EXEGGCUTE_A] = OBJ_EVENT_PAL_TAG_EXEGGCUTE_SHINY,
    [SPECIES_EXEGGUTOR_A] = OBJ_EVENT_PAL_TAG_EXEGGUTOR_A_SHINY,
    [SPECIES_CUBONE_A] = OBJ_EVENT_PAL_TAG_CUBONE_SHINY,
    [SPECIES_MAROWAK_A] = OBJ_EVENT_PAL_TAG_MAROWAK_A_SHINY,
    [SPECIES_DEOXYS_ATTACK] = OBJ_EVENT_PAL_TAG_DEOXYS_SHINY,
    [SPECIES_DEOXYS_DEFENSE] = OBJ_EVENT_PAL_TAG_DEOXYS_SHINY,
    [SPECIES_DEOXYS_SPEED] = OBJ_EVENT_PAL_TAG_DEOXYS_SHINY,
    [SPECIES_ORICORIO_Y] = OBJ_EVENT_PAL_TAG_ORICORIO_SHINY,
    [SPECIES_ORICORIO_P] = OBJ_EVENT_PAL_TAG_ORICORIO_SHINY,
    [SPECIES_ORICORIO_S] = OBJ_EVENT_PAL_TAG_ORICORIO_SHINY,
    [SPECIES_LYCANROC_N] = OBJ_EVENT_PAL_TAG_LYCANROC_N_SHINY,
    [SPECIES_SILVALLY_FIGHT] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_FLYING] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_POISON] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_GROUND] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_ROCK] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_BUG] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_GHOST] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_STEEL] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_FIRE] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_WATER] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_GRASS] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_ELECTRIC] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_PSYCHIC] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_ICE] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_DRAGON] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_DARK] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_SILVALLY_FAIRY] = OBJ_EVENT_PAL_TAG_SILVALLY_SHINY,
    [SPECIES_MINIOR_RED] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_BLUE] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_ORANGE] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_YELLOW] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_INDIGO] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_GREEN] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MINIOR_VIOLET] = OBJ_EVENT_PAL_TAG_MINIOR_SHINY,
    [SPECIES_MAGEARNA_P] = OBJ_EVENT_PAL_TAG_MAGEARNA_SHINY,
    [SPECIES_POIPOLE] = OBJ_EVENT_PAL_TAG_POIPOLE_SHINY,
    [SPECIES_NAGANADEL] = OBJ_EVENT_PAL_TAG_NAGANADEL_SHINY,
    [SPECIES_STAKATAKA] = OBJ_EVENT_PAL_TAG_STAKATAKA_SHINY,
    [SPECIES_BLACEPHALON] = OBJ_EVENT_PAL_TAG_BLACEPHALON_SHINY,
    [SPECIES_ZERAORA] = OBJ_EVENT_PAL_TAG_ZERAORA_SHINY,
    [SPECIES_NECROZMA_DUSK_MANE] = OBJ_EVENT_PAL_TAG_NECROZMA_DM_SHINY,
    [SPECIES_NECROZMA_DAWN_WINGS] = OBJ_EVENT_PAL_TAG_NECROZMA_DW_SHINY,
    [SPECIES_LYCANROC_DUSK] = OBJ_EVENT_PAL_TAG_LYCANROC_D_SHINY,
    [SPECIES_MELTAN] = OBJ_EVENT_PAL_TAG_MELTAN_SHINY,
    [SPECIES_MELMETAL] = OBJ_EVENT_PAL_TAG_MELMETAL_SHINY,
    [SPECIES_PIKACHU_SURFING] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_FLYING] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_COSPLAY] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_LIBRE] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_POP_STAR] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_ROCK_STAR] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_BELLE] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_PHD] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_ORIGINAL] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_HOENN] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_SINNOH] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_UNOVA] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_KALOS] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_ALOLA] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PIKACHU_CAP_PARTNER] = OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
    [SPECIES_PICHU_SPIKY] = OBJ_EVENT_PAL_TAG_PICHU_S_SHINY,
    [SPECIES_XERNEAS_NATURAL] = OBJ_EVENT_PAL_TAG_XERNEAS_SHINY,
    [SPECIES_GROOKEY] = OBJ_EVENT_PAL_TAG_GROOKEY_SHINY,
    [SPECIES_THWACKEY] = OBJ_EVENT_PAL_TAG_THWACKEY_SHINY,
    [SPECIES_RILLABOOM] = OBJ_EVENT_PAL_TAG_RILLABOOM_SHINY,
    [SPECIES_SCORBUNNY] = OBJ_EVENT_PAL_TAG_SCORBUNNY_SHINY,
    [SPECIES_RABOOT] = OBJ_EVENT_PAL_TAG_RABOOT_SHINY,
    [SPECIES_CINDERACE] = OBJ_EVENT_PAL_TAG_CINDERACE_SHINY,
    [SPECIES_SOBBLE] = OBJ_EVENT_PAL_TAG_SOBBLE_SHINY,
    [SPECIES_DRIZZILE] = OBJ_EVENT_PAL_TAG_DRIZZILE_SHINY,
    [SPECIES_INTELEON] = OBJ_EVENT_PAL_TAG_INTELEON_SHINY,
    [SPECIES_SKWOVET] = OBJ_EVENT_PAL_TAG_SKWOVET_SHINY,
    [SPECIES_GREEDENT] = OBJ_EVENT_PAL_TAG_GREEDENT_SHINY,
    [SPECIES_ROOKIDEE] = OBJ_EVENT_PAL_TAG_ROOKIDEE_SHINY,
    [SPECIES_CORVISQUIRE] = OBJ_EVENT_PAL_TAG_CORVISQUIRE_SHINY,
    [SPECIES_CORVIKNIGHT] = OBJ_EVENT_PAL_TAG_CORVIKNIGHT_SHINY,
    [SPECIES_BLIPBUG] = OBJ_EVENT_PAL_TAG_BLIPBUG_SHINY,
    [SPECIES_DOTTLER] = OBJ_EVENT_PAL_TAG_DOTTLER_SHINY,
    [SPECIES_ORBEETLE] = OBJ_EVENT_PAL_TAG_ORBEETLE_SHINY,
    [SPECIES_NICKIT] = OBJ_EVENT_PAL_TAG_NICKIT_SHINY,
    [SPECIES_THIEVUL] = OBJ_EVENT_PAL_TAG_THIEVUL_SHINY,
    [SPECIES_GOSSIFLEUR] = OBJ_EVENT_PAL_TAG_GOSSIFLEUR_SHINY,
    [SPECIES_ELDEGOSS] = OBJ_EVENT_PAL_TAG_ELDEGOSS_SHINY,
    [SPECIES_WOOLOO] = OBJ_EVENT_PAL_TAG_WOOLOO_SHINY,
    [SPECIES_DUBWOOL] = OBJ_EVENT_PAL_TAG_DUBWOOL_SHINY,
    [SPECIES_CHEWTLE] = OBJ_EVENT_PAL_TAG_CHEWTLE_SHINY,
    [SPECIES_DREDNAW] = OBJ_EVENT_PAL_TAG_DREDNAW_SHINY,
    [SPECIES_YAMPER] = OBJ_EVENT_PAL_TAG_YAMPER_SHINY,
    [SPECIES_BOLTUND] = OBJ_EVENT_PAL_TAG_BOLTUND_SHINY,
    [SPECIES_ROLYCOLY] = OBJ_EVENT_PAL_TAG_ROLYCOLY_SHINY,
    [SPECIES_CARKOL] = OBJ_EVENT_PAL_TAG_CARKOL_SHINY,
    [SPECIES_COALOSSAL] = OBJ_EVENT_PAL_TAG_COALOSSAL_SHINY,
    [SPECIES_APPLIN] = OBJ_EVENT_PAL_TAG_APPLIN_SHINY,
    [SPECIES_FLAPPLE] = OBJ_EVENT_PAL_TAG_FLAPPLE_SHINY,
    [SPECIES_APPLETUN] = OBJ_EVENT_PAL_TAG_APPLETUN_SHINY,
    [SPECIES_SILICOBRA] = OBJ_EVENT_PAL_TAG_SILICOBRA_SHINY,
    [SPECIES_SANDACONDA] = OBJ_EVENT_PAL_TAG_SANDACONDA_SHINY,
    [SPECIES_CRAMORANT] = OBJ_EVENT_PAL_TAG_CRAMORANT_SHINY,
    [SPECIES_ARROKUDA] = OBJ_EVENT_PAL_TAG_ARROKUDA_SHINY,
    [SPECIES_BARRASKEWDA] = OBJ_EVENT_PAL_TAG_BARRASKEWDA_SHINY,
    [SPECIES_TOXEL] = OBJ_EVENT_PAL_TAG_TOXEL_SHINY,
    [SPECIES_TOXTRICITY] = OBJ_EVENT_PAL_TAG_TOXTRICITY_SHINY,
    [SPECIES_SIZZLIPEDE] = OBJ_EVENT_PAL_TAG_SIZZLIPEDE_SHINY,
    [SPECIES_CENTISKORCH] = OBJ_EVENT_PAL_TAG_CENTISKORCH_SHINY,
    [SPECIES_CLOBBOPUS] = OBJ_EVENT_PAL_TAG_CLOBBOPUS_SHINY,
    [SPECIES_GRAPPLOCT] = OBJ_EVENT_PAL_TAG_GRAPPLOCT_SHINY,
    [SPECIES_SINISTEA] = OBJ_EVENT_PAL_TAG_SINISTEA_SHINY,
    [SPECIES_POLTEAGEIST] = OBJ_EVENT_PAL_TAG_POLTEAGEIST_SHINY,
    [SPECIES_HATENNA] = OBJ_EVENT_PAL_TAG_HATENNA_SHINY,
    [SPECIES_HATTREM] = OBJ_EVENT_PAL_TAG_HATTREM_SHINY,
    [SPECIES_HATTERENE] = OBJ_EVENT_PAL_TAG_HATTERENE_SHINY,
    [SPECIES_IMPIDIMP] = OBJ_EVENT_PAL_TAG_IMPIDIMP_SHINY,
    [SPECIES_MORGREM] = OBJ_EVENT_PAL_TAG_MORGREM_SHINY,
    [SPECIES_GRIMMSNARL] = OBJ_EVENT_PAL_TAG_GRIMMSNARL_SHINY,
    [SPECIES_OBSTAGOON] = OBJ_EVENT_PAL_TAG_OBSTAGOON_SHINY,
    [SPECIES_PERRSERKER] = OBJ_EVENT_PAL_TAG_PERRSERKER_SHINY,
    [SPECIES_CURSOLA] = OBJ_EVENT_PAL_TAG_CURSOLA_SHINY,
    [SPECIES_SIRFETCHD] = OBJ_EVENT_PAL_TAG_SIRFETCHD_SHINY,
    [SPECIES_MR_RIME] = OBJ_EVENT_PAL_TAG_MR_RIME_SHINY,
    [SPECIES_RUNERIGUS] = OBJ_EVENT_PAL_TAG_RUNERIGUS_SHINY,
    [SPECIES_MILCERY] = OBJ_EVENT_PAL_TAG_MILCERY_SHINY,
    [SPECIES_ALCREMIE_STRAWBERRY] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_FALINKS] = OBJ_EVENT_PAL_TAG_FALINKS_SHINY,
    [SPECIES_PINCURCHIN] = OBJ_EVENT_PAL_TAG_PINCURCHIN_SHINY,
    [SPECIES_SNOM] = OBJ_EVENT_PAL_TAG_SNOM_SHINY,
    [SPECIES_FROSMOTH] = OBJ_EVENT_PAL_TAG_FROSMOTH_SHINY,
    [SPECIES_STONJOURNER] = OBJ_EVENT_PAL_TAG_STONJOURNER_SHINY,
    [SPECIES_EISCUE] = OBJ_EVENT_PAL_TAG_EISCUE_SHINY,
    [SPECIES_INDEEDEE] = OBJ_EVENT_PAL_TAG_INDEEDEE_SHINY,
    [SPECIES_MORPEKO] = OBJ_EVENT_PAL_TAG_MORPEKO_SHINY,
    [SPECIES_CUFANT] = OBJ_EVENT_PAL_TAG_CUFANT_SHINY,
    [SPECIES_COPPERAJAH] = OBJ_EVENT_PAL_TAG_COPPERAJAH_SHINY,
    [SPECIES_DRACOZOLT] = OBJ_EVENT_PAL_TAG_DRACOZOLT_SHINY,
    [SPECIES_ARCTOZOLT] = OBJ_EVENT_PAL_TAG_ARCTOZOLT_SHINY,
    [SPECIES_DRACOVISH] = OBJ_EVENT_PAL_TAG_DRACOVISH_SHINY,
    [SPECIES_ARCTOVISH] = OBJ_EVENT_PAL_TAG_ARCTOVISH_SHINY,
    [SPECIES_DURALUDON] = OBJ_EVENT_PAL_TAG_DURALUDON_SHINY,
    [SPECIES_DREEPY] = OBJ_EVENT_PAL_TAG_DREEPY_SHINY,
    [SPECIES_DRAKLOAK] = OBJ_EVENT_PAL_TAG_DRAKLOAK_SHINY,
    [SPECIES_DRAGAPULT] = OBJ_EVENT_PAL_TAG_DRAGAPULT_SHINY,
    [SPECIES_ZACIAN] = OBJ_EVENT_PAL_TAG_ZACIAN_SHINY,
    [SPECIES_ZAMAZENTA] = OBJ_EVENT_PAL_TAG_ZAMAZENTA_SHINY,
    [SPECIES_ETERNATUS] = OBJ_EVENT_PAL_TAG_ETERNATUS_SHINY,
    [SPECIES_KUBFU] = OBJ_EVENT_PAL_TAG_KUBFU_SHINY,
    [SPECIES_URSHIFU_SINGLE] = OBJ_EVENT_PAL_TAG_URSHIFU_SHINY,
    [SPECIES_ZARUDE] = OBJ_EVENT_PAL_TAG_ZARUDE_SHINY,
    [SPECIES_REGIELEKI] = OBJ_EVENT_PAL_TAG_REGIELEKI_SHINY,
    [SPECIES_REGIDRAGO] = OBJ_EVENT_PAL_TAG_REGIDRAGO_SHINY,
    [SPECIES_GLASTRIER] = OBJ_EVENT_PAL_TAG_GLASTRIER_SHINY,
    [SPECIES_SPECTRIER] = OBJ_EVENT_PAL_TAG_SPECTRIER_SHINY,
    [SPECIES_CALYREX] = OBJ_EVENT_PAL_TAG_CALYREX_SHINY,
    [SPECIES_TOXTRICITY_LOW_KEY] = OBJ_EVENT_PAL_TAG_TOXTRICITY_LK_SHINY,
    [SPECIES_SINISTEA_CHIPPED] = OBJ_EVENT_PAL_TAG_SINISTEA_SHINY,
    [SPECIES_POLTEAGEIST_CHIPPED] = OBJ_EVENT_PAL_TAG_POLTEAGEIST_SHINY,
    [SPECIES_ALCREMIE_BERRY] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_ALCREMIE_CLOVER] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_ALCREMIE_FLOWER] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_ALCREMIE_LOVE] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_ALCREMIE_RIBBON] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_ALCREMIE_STAR] = OBJ_EVENT_PAL_TAG_ALCREMIE_SHINY,
    [SPECIES_INDEEDEE_FEMALE] = OBJ_EVENT_PAL_TAG_INDEEDEE_F_SHINY,
    [SPECIES_ZACIAN_CROWNED] = OBJ_EVENT_PAL_TAG_ZACIAN_C_SHINY,
    [SPECIES_ZAMAZENTA_CROWNED] = OBJ_EVENT_PAL_TAG_ZAMAZENTA_C_SHINY,
    [SPECIES_URSHIFU_RAPID] = OBJ_EVENT_PAL_TAG_URSHIFU_SHINY,
    [SPECIES_ZARUDE_DADA] = OBJ_EVENT_PAL_TAG_ZARUDE_SHINY,
    [SPECIES_CALYREX_ICE_RIDER] = OBJ_EVENT_PAL_TAG_CALYREX_IR_SHINY,
    [SPECIES_CALYREX_SHADOW_RIDER] = OBJ_EVENT_PAL_TAG_CALYREX_SR_SHINY,
    [SPECIES_MEOWTH_G] = OBJ_EVENT_PAL_TAG_MEOWTH_G_SHINY,
    [SPECIES_PONYTA_G] = OBJ_EVENT_PAL_TAG_PONYTA_G_SHINY,
    [SPECIES_RAPIDASH_G] = OBJ_EVENT_PAL_TAG_RAPIDASH_G_SHINY,
    [SPECIES_SLOWPOKE_G] = OBJ_EVENT_PAL_TAG_SLOWPOKE_G_SHINY,
    [SPECIES_SLOWBRO_G] = OBJ_EVENT_PAL_TAG_SLOWBRO_G_SHINY,
    [SPECIES_FARFETCHD_G] = OBJ_EVENT_PAL_TAG_FARFETCHD_G_SHINY,
    [SPECIES_KOFFING_G] = OBJ_EVENT_PAL_TAG_KOFFING_SHINY,
    [SPECIES_WEEZING_G] = OBJ_EVENT_PAL_TAG_WEEZING_G_SHINY,
    [SPECIES_MR_MIME_G] = OBJ_EVENT_PAL_TAG_MR_MIME_G_SHINY,
    [SPECIES_ARTICUNO_G] = OBJ_EVENT_PAL_TAG_ARTICUNO_G_SHINY,
    [SPECIES_ZAPDOS_G] = OBJ_EVENT_PAL_TAG_ZAPDOS_G_SHINY,
    [SPECIES_MOLTRES_G] = OBJ_EVENT_PAL_TAG_MOLTRES_G_SHINY,
    [SPECIES_SLOWKING_G] = OBJ_EVENT_PAL_TAG_SLOWKING_G_SHINY,
    [SPECIES_CORSOLA_G] = OBJ_EVENT_PAL_TAG_CORSOLA_G_SHINY,
    [SPECIES_ZIGZAGOON_G] = OBJ_EVENT_PAL_TAG_ZIGZAGOON_G_SHINY,
    [SPECIES_LINOONE_G] = OBJ_EVENT_PAL_TAG_LINOONE_G_SHINY,
    [SPECIES_MIME_JR_G] = OBJ_EVENT_PAL_TAG_MIME_JR_SHINY,
    [SPECIES_DARUMAKA_G] = OBJ_EVENT_PAL_TAG_DARUMAKA_G_SHINY,
    [SPECIES_DARMANITAN_G] = OBJ_EVENT_PAL_TAG_DARMANITAN_G_SHINY,
    [SPECIES_YAMASK_G] = OBJ_EVENT_PAL_TAG_YAMASK_G_SHINY,
    [SPECIES_STUNFISK_G] = OBJ_EVENT_PAL_TAG_STUNFISK_G_SHINY,
    [SPECIES_GROWLITHE_H] = OBJ_EVENT_PAL_TAG_GROWLITHE_H_SHINY,
    [SPECIES_ARCANINE_H] = OBJ_EVENT_PAL_TAG_ARCANINE_H_SHINY,
    [SPECIES_VOLTORB_H] = OBJ_EVENT_PAL_TAG_VOLTORB_H_SHINY,
    [SPECIES_ELECTRODE_H] = OBJ_EVENT_PAL_TAG_ELECTRODE_H_SHINY,
    [SPECIES_TYPHLOSION_H] = OBJ_EVENT_PAL_TAG_TYPHLOSION_H_SHINY,
    [SPECIES_QWILFISH_H] = OBJ_EVENT_PAL_TAG_QWILFISH_H_SHINY,
    [SPECIES_SNEASEL_H] = OBJ_EVENT_PAL_TAG_SNEASEL_H_SHINY,
    [SPECIES_SAMUROTT_H] = OBJ_EVENT_PAL_TAG_SAMUROTT_1_SHINY,
    [SPECIES_LILLIGANT_H] = OBJ_EVENT_PAL_TAG_LILLIGANT_H_SHINY,
    [SPECIES_BASCULIN_H] = OBJ_EVENT_PAL_TAG_BASCULIN_W_SHINY,
    [SPECIES_ZORUA_H] = OBJ_EVENT_PAL_TAG_ZORUA_H_SHINY,
    [SPECIES_ZOROARK_H] = OBJ_EVENT_PAL_TAG_ZOROARK_H_SHINY,
    [SPECIES_BRAVIARY_H] = OBJ_EVENT_PAL_TAG_BRAVIARY_H_SHINY,
    [SPECIES_SLIGGOO_H] = OBJ_EVENT_PAL_TAG_SLIGGOO_H_SHINY,
    [SPECIES_GOODRA_H] = OBJ_EVENT_PAL_TAG_GOODRA_H_SHINY,
    [SPECIES_AVALUGG_H] = OBJ_EVENT_PAL_TAG_AVALUGG_H_SHINY,
    [SPECIES_DECIDUEYE_H] = OBJ_EVENT_PAL_TAG_DECIDUEYE_H_SHINY,
    [SPECIES_WYRDEER] = OBJ_EVENT_PAL_TAG_WYRDEER_SHINY,
    [SPECIES_KLEAVOR] = OBJ_EVENT_PAL_TAG_KLEAVOR_SHINY,
    [SPECIES_URSALUNA] = OBJ_EVENT_PAL_TAG_URSALUNA_SHINY,
    [SPECIES_BASCULEGION_M] = OBJ_EVENT_PAL_TAG_BASCULEGION_SHINY,
    [SPECIES_BASCULEGION_F] = OBJ_EVENT_PAL_TAG_BASCULEGION_F_SHINY,
    [SPECIES_SNEASLER] = OBJ_EVENT_PAL_TAG_SNEASLER_SHINY,
    [SPECIES_OVERQWIL] = OBJ_EVENT_PAL_TAG_OVERQWIL_SHINY,
    [SPECIES_ENAMORUS] = OBJ_EVENT_PAL_TAG_ENAMORUS_SHINY,
    [SPECIES_ENAMORUS_THERIAN] = OBJ_EVENT_PAL_TAG_ENAMORUS_T_SHINY,
    [SPECIES_SPRIGATITO] = OBJ_EVENT_PAL_TAG_SPRIGATITO_SHINY,
    [SPECIES_FLORAGATO] = OBJ_EVENT_PAL_TAG_FLORAGATO_SHINY,
    [SPECIES_MEOWSCARADA] = OBJ_EVENT_PAL_TAG_MEOWSCARADA_SHINY,
    [SPECIES_FUECOCO] = OBJ_EVENT_PAL_TAG_FUECOCO_SHINY,
    [SPECIES_CROCALOR] = OBJ_EVENT_PAL_TAG_CROCALOR_SHINY,
    [SPECIES_SKELEDIRGE] = OBJ_EVENT_PAL_TAG_SKELEDIRGE_SHINY,
    [SPECIES_QUAXLY] = OBJ_EVENT_PAL_TAG_QUAXLY_SHINY,
    [SPECIES_QUAXWELL] = OBJ_EVENT_PAL_TAG_QUAXWELL_SHINY,
    [SPECIES_QUAQUAVAL] = OBJ_EVENT_PAL_TAG_QUAQUAVAL_SHINY,
    [SPECIES_LECHONK] = OBJ_EVENT_PAL_TAG_LECHONK_SHINY,
    [SPECIES_OINKOLOGNE] = OBJ_EVENT_PAL_TAG_OINKOLOGNE_SHINY,
    [SPECIES_TAROUNTULA] = OBJ_EVENT_PAL_TAG_TAROUNTULA_SHINY,
    [SPECIES_SPIDOPS] = OBJ_EVENT_PAL_TAG_SPIDOPS_SHINY,
    [SPECIES_NYMBLE] = OBJ_EVENT_PAL_TAG_NYMBLE_SHINY,
    [SPECIES_LOKIX] = OBJ_EVENT_PAL_TAG_LOKIX_SHINY,
    [SPECIES_PAWMI] = OBJ_EVENT_PAL_TAG_PAWMI_SHINY,
    [SPECIES_PAWMO] = OBJ_EVENT_PAL_TAG_PAWMO_SHINY,
    [SPECIES_PAWMOT] = OBJ_EVENT_PAL_TAG_PAWMOT_SHINY,
    [SPECIES_TANDEMAUS] = OBJ_EVENT_PAL_TAG_TANDEMAUS_SHINY,
    [SPECIES_MAUSHOLD] = OBJ_EVENT_PAL_TAG_MAUSHOLD_SHINY,
    [SPECIES_FIDOUGH] = OBJ_EVENT_PAL_TAG_FIDOUGH_SHINY,
    [SPECIES_DACHSBUN] = OBJ_EVENT_PAL_TAG_DACHSBUN_SHINY,
    [SPECIES_SMOLIV] = OBJ_EVENT_PAL_TAG_SMOLIV_SHINY,
    [SPECIES_DOLLIV] = OBJ_EVENT_PAL_TAG_DOLLIV_SHINY,
    [SPECIES_ARBOLIVA] = OBJ_EVENT_PAL_TAG_ARBOLIVA_SHINY,
    [SPECIES_SQUAWKABILLY] = OBJ_EVENT_PAL_TAG_SQUAWKABILLY_SHINY,
    [SPECIES_NACLI] = OBJ_EVENT_PAL_TAG_NACLI_SHINY,
    [SPECIES_NACLSTACK] = OBJ_EVENT_PAL_TAG_NACLSTACK_SHINY,
    [SPECIES_GARGANACL] = OBJ_EVENT_PAL_TAG_GARGANACL_SHINY,
    [SPECIES_CHARCADET] = OBJ_EVENT_PAL_TAG_CHARCADET_SHINY,
    [SPECIES_ARMAROUGE] = OBJ_EVENT_PAL_TAG_ARMAROUGE_SHINY,
    [SPECIES_CERULEDGE] = OBJ_EVENT_PAL_TAG_CERULEDGE_SHINY,
    [SPECIES_TADBULB] = OBJ_EVENT_PAL_TAG_TADBULB_SHINY,
    [SPECIES_BELLIBOLT] = OBJ_EVENT_PAL_TAG_BELLIBOLT_SHINY,
    [SPECIES_WATTREL] = OBJ_EVENT_PAL_TAG_WATTREL_SHINY,
    [SPECIES_KILOWATTREL] = OBJ_EVENT_PAL_TAG_KILOWATTREL_SHINY,
    [SPECIES_MASCHIFF] = OBJ_EVENT_PAL_TAG_MASCHIFF_SHINY,
    [SPECIES_MABOSSTIFF] = OBJ_EVENT_PAL_TAG_MABOSSTIFF_SHINY,
    [SPECIES_SHROODLE] = OBJ_EVENT_PAL_TAG_SHROODLE_SHINY,
    [SPECIES_GRAFAIAI] = OBJ_EVENT_PAL_TAG_GRAFAIAI_SHINY,
    [SPECIES_BRAMBLIN] = OBJ_EVENT_PAL_TAG_BRAMBLIN_SHINY,
    [SPECIES_BRAMBLEGHAST] = OBJ_EVENT_PAL_TAG_BRAMBLEGHAST_SHINY,
    [SPECIES_TOEDSCOOL] = OBJ_EVENT_PAL_TAG_TOEDSCOOL_SHINY,
    [SPECIES_TOEDSCRUEL] = OBJ_EVENT_PAL_TAG_TOEDSCRUEL_SHINY,
    [SPECIES_KLAWF] = OBJ_EVENT_PAL_TAG_KLAWF_SHINY,
    [SPECIES_CAPSAKID] = OBJ_EVENT_PAL_TAG_CAPSAKID_SHINY,
    [SPECIES_SCOVILLAIN] = OBJ_EVENT_PAL_TAG_SCOVILLAIN_SHINY,
    [SPECIES_RELLOR] = OBJ_EVENT_PAL_TAG_RELLOR_SHINY,
    [SPECIES_RABSCA] = OBJ_EVENT_PAL_TAG_RABSCA_SHINY,
    [SPECIES_FLITTLE] = OBJ_EVENT_PAL_TAG_FLITTLE_SHINY,
    [SPECIES_ESPATHRA] = OBJ_EVENT_PAL_TAG_ESPATHRA_SHINY,
    [SPECIES_TINKATINK] = OBJ_EVENT_PAL_TAG_TINKATINK_SHINY,
    [SPECIES_TINKATUFF] = OBJ_EVENT_PAL_TAG_TINKATUFF_SHINY,
    [SPECIES_TINKATON] = OBJ_EVENT_PAL_TAG_TINKATON_SHINY,
    [SPECIES_WIGLETT] = OBJ_EVENT_PAL_TAG_WIGLETT_SHINY,
    [SPECIES_WUGTRIO] = OBJ_EVENT_PAL_TAG_WUGTRIO_SHINY,
    [SPECIES_BOMBIRDIER] = OBJ_EVENT_PAL_TAG_BOMBIRDIER_SHINY,
    [SPECIES_FINIZEN] = OBJ_EVENT_PAL_TAG_FINIZEN_SHINY,
    [SPECIES_PALAFIN] = OBJ_EVENT_PAL_TAG_PALAFIN_SHINY,
    [SPECIES_VAROOM] = OBJ_EVENT_PAL_TAG_VAROOM_SHINY,
    [SPECIES_REVAVROOM] = OBJ_EVENT_PAL_TAG_REVAVROOM_SHINY,
    [SPECIES_CYCLIZAR] = OBJ_EVENT_PAL_TAG_CYCLIZAR_SHINY,
    [SPECIES_ORTHWORM] = OBJ_EVENT_PAL_TAG_ORTHWORM_SHINY,
    [SPECIES_GLIMMET] = OBJ_EVENT_PAL_TAG_GLIMMET_SHINY,
    [SPECIES_GLIMMORA] = OBJ_EVENT_PAL_TAG_GLIMMORA_SHINY,
    [SPECIES_GREAVARD] = OBJ_EVENT_PAL_TAG_GREAVARD_SHINY,
    [SPECIES_HOUNDSTONE] = OBJ_EVENT_PAL_TAG_HOUNDSTONE_SHINY,
    [SPECIES_FLAMIGO] = OBJ_EVENT_PAL_TAG_FLAMIGO_SHINY,
    [SPECIES_CETODDLE] = OBJ_EVENT_PAL_TAG_CETODDLE_SHINY,
    [SPECIES_CETITAN] = OBJ_EVENT_PAL_TAG_CETITAN_SHINY,
    [SPECIES_VELUZA] = OBJ_EVENT_PAL_TAG_VELUZA_SHINY,
    [SPECIES_DONDOZO] = OBJ_EVENT_PAL_TAG_DONDOZO_SHINY,
    [SPECIES_TATSUGIRI] = OBJ_EVENT_PAL_TAG_TATSUGIRI_SHINY,
    [SPECIES_ANNIHILAPE] = OBJ_EVENT_PAL_TAG_ANNIHILAPE_SHINY,
    [SPECIES_CLODSIRE] = OBJ_EVENT_PAL_TAG_CLODSIRE_SHINY,
    [SPECIES_FARIGIRAF] = OBJ_EVENT_PAL_TAG_FARIGIRAF_SHINY,
    [SPECIES_DUDUNSPARCE] = OBJ_EVENT_PAL_TAG_DUDUNSPARCE_SHINY,
    [SPECIES_KINGAMBIT] = OBJ_EVENT_PAL_TAG_KINGAMBIT_SHINY,
    [SPECIES_GREAT_TUSK] = OBJ_EVENT_PAL_TAG_GREAT_TUSK_SHINY,
    [SPECIES_SCREAM_TAIL] = OBJ_EVENT_PAL_TAG_SCREAM_TAIL_SHINY,
    [SPECIES_BRUTE_BONNET] = OBJ_EVENT_PAL_TAG_BRUTE_BONNET_SHINY,
    [SPECIES_FLUTTER_MANE] = OBJ_EVENT_PAL_TAG_FLUTTER_MANE_SHINY,
    [SPECIES_SLITHER_WING] = OBJ_EVENT_PAL_TAG_SLITHER_WING_SHINY,
    [SPECIES_SANDY_SHOCKS] = OBJ_EVENT_PAL_TAG_SANDY_SHOCKS_SHINY,
    [SPECIES_IRON_TREADS] = OBJ_EVENT_PAL_TAG_IRON_TREADS_SHINY,
    [SPECIES_IRON_BUNDLE] = OBJ_EVENT_PAL_TAG_IRON_BUNDLE_SHINY,
    [SPECIES_IRON_HANDS] = OBJ_EVENT_PAL_TAG_IRON_HANDS_SHINY,
    [SPECIES_IRON_JUGULIS] = OBJ_EVENT_PAL_TAG_IRON_JUGULIS_SHINY,
    [SPECIES_IRON_MOTH] = OBJ_EVENT_PAL_TAG_IRON_MOTH_SHINY,
    [SPECIES_IRON_THORNS] = OBJ_EVENT_PAL_TAG_IRON_THORNS_SHINY,
    [SPECIES_FRIGIBAX] = OBJ_EVENT_PAL_TAG_FRIGIBAX_SHINY,
    [SPECIES_ARCTIBAX] = OBJ_EVENT_PAL_TAG_ARCTIBAX_SHINY,
    [SPECIES_BAXCALIBUR] = OBJ_EVENT_PAL_TAG_BAXCALIBUR_SHINY,
    [SPECIES_GIMMIGHOUL] = OBJ_EVENT_PAL_TAG_GIMMIGHOUL_SHINY,
    [SPECIES_GHOLDENGO] = OBJ_EVENT_PAL_TAG_GHOLDENGO_SHINY,
    [SPECIES_WO_CHIEN] = OBJ_EVENT_PAL_TAG_WO_CHIEN_SHINY,
    [SPECIES_CHIEN_PAO] = OBJ_EVENT_PAL_TAG_CHIEN_PAO_SHINY,
    [SPECIES_TING_LU] = OBJ_EVENT_PAL_TAG_TING_LU_SHINY,
    [SPECIES_CHI_YU] = OBJ_EVENT_PAL_TAG_CHI_YU_SHINY,
    [SPECIES_ROARING_MOON] = OBJ_EVENT_PAL_TAG_ROARING_MOON_SHINY,
    [SPECIES_IRON_VALIANT] = OBJ_EVENT_PAL_TAG_IRON_VALIANT_SHINY,
    [SPECIES_KORAIDON] = OBJ_EVENT_PAL_TAG_KORAIDON_SHINY,
    [SPECIES_MIRAIDON] = OBJ_EVENT_PAL_TAG_MIRAIDON_SHINY,
    [SPECIES_WALKING_WAKE] = OBJ_EVENT_PAL_TAG_WALKING_WAKE_SHINY,
    [SPECIES_IRON_LEAVES] = OBJ_EVENT_PAL_TAG_IRON_LEAVES_SHINY,
    [SPECIES_OINKOLOGNE_FEMALE] = OBJ_EVENT_PAL_TAG_OINKOLOGNE_F_SHINY,
    [SPECIES_SQUAWKABILLY_BLUE] = OBJ_EVENT_PAL_TAG_SQUAWKABILLY_B_SHINY,
    [SPECIES_SQUAWKABILLY_YELLOW] = OBJ_EVENT_PAL_TAG_SQUAWKABILLY_Y_SHINY,
    [SPECIES_SQUAWKABILLY_WHITE] = OBJ_EVENT_PAL_TAG_SQUAWKABILLY_W_SHINY,
    [SPECIES_TATSUGIRI_RED] = OBJ_EVENT_PAL_TAG_TATSUGIRI_SHINY,
    [SPECIES_TATSUGIRI_YELLOW] = OBJ_EVENT_PAL_TAG_TATSUGIRI_SHINY,
    [SPECIES_DUDUNSPARCE_THREE] = OBJ_EVENT_PAL_TAG_DUDUNSPARCE_2_SHINY,
    [SPECIES_TAUROS_P] = OBJ_EVENT_PAL_TAG_TAUROS_C_SHINY,
    [SPECIES_TAUROS_BLAZE_P] = OBJ_EVENT_PAL_TAG_TAUROS_B_SHINY,
    [SPECIES_TAUROS_AQUA_P] = OBJ_EVENT_PAL_TAG_TAUROS_A_SHINY,
    [SPECIES_WOOPER_P] = OBJ_EVENT_PAL_TAG_WOOPER_P_SHINY,
    [SPECIES_DIPPLIN] = OBJ_EVENT_PAL_TAG_DIPPLIN_SHINY,
    [SPECIES_POLTCHAGEIST] = OBJ_EVENT_PAL_TAG_POLTCHAGEIST_SHINY,
    [SPECIES_SINISTCHA] = OBJ_EVENT_PAL_TAG_SINISTCHA_SHINY,
    [SPECIES_OKIDOGI] = OBJ_EVENT_PAL_TAG_OKIDOGI_SHINY,
    [SPECIES_MUNKIDORI] = OBJ_EVENT_PAL_TAG_MUNKIDORI_SHINY,
    [SPECIES_FEZANDIPITI] = OBJ_EVENT_PAL_TAG_FEZANDIPITI_SHINY,
    [SPECIES_OGERPON] = OBJ_EVENT_PAL_TAG_OGERPON_SHINY,
    [SPECIES_OGERPON_WELLSPRING_MASK] = OBJ_EVENT_PAL_TAG_OGERPON_1_SHINY,
    [SPECIES_OGERPON_HEARTHFLAME_MASK] = OBJ_EVENT_PAL_TAG_OGERPON_2_SHINY,
    [SPECIES_OGERPON_CORNERSTONE_MASK] = OBJ_EVENT_PAL_TAG_OGERPON_3_SHINY,
    [SPECIES_ARCHALUDON] = OBJ_EVENT_PAL_TAG_ARCHALUDON_SHINY,
    [SPECIES_HYDRAPPLE] = OBJ_EVENT_PAL_TAG_HYDRAPPLE_SHINY,
    [SPECIES_GOUGING_FIRE] = OBJ_EVENT_PAL_TAG_GOUGING_FIRE_SHINY,
    [SPECIES_RAGING_BOLT] = OBJ_EVENT_PAL_TAG_RAGING_BOLT_SHINY,
    [SPECIES_IRON_BOULDER] = OBJ_EVENT_PAL_TAG_IRON_BOULDER_SHINY,
    [SPECIES_IRON_CROWN] = OBJ_EVENT_PAL_TAG_IRON_CROWN_SHINY,
    [SPECIES_TERAPAGOS] = OBJ_EVENT_PAL_TAG_TERAPAGOS_SHINY,
    [SPECIES_TERAPAGOS_TERASTAL] = OBJ_EVENT_PAL_TAG_TERAPAGOS_1_SHINY,
    [SPECIES_PECHARUNT] = OBJ_EVENT_PAL_TAG_PECHARUNT_SHINY,
    [SPECIES_URSALUNA_BLOODMOON] = OBJ_EVENT_PAL_TAG_URSALUNA_BM_SHINY,
    [SPECIES_MAUSHOLD_FOUR] = OBJ_EVENT_PAL_TAG_MAUSHOLD_F_SHINY,
    [SPECIES_GIMMIGHOUL_ROAMING] = OBJ_EVENT_PAL_TAG_GIMMIGHOUL_SHINY,
    [SPECIES_DIALGA_ORIGIN] = OBJ_EVENT_PAL_TAG_DIALGA_SHINY,
    [SPECIES_PALKIA_ORIGIN] = OBJ_EVENT_PAL_TAG_PALKIA_SHINY,
};

void ChangeFollowerPalette(void)
{
    u8 followerId = GetFollowerMapObjId();
    if (followerId >= MAP_OBJECTS_COUNT)
        return;

    struct EventObject* follower = &gEventObjects[followerId];
    if (!follower->active)
        return;

    u8 spriteId = follower->spriteId;
    if (spriteId >= MAX_SPRITES)
        return;

    struct Pokemon* mon = GetFirstValidPartyMon();
    if (mon == NULL)
        return;

    if (!IsMonShiny(mon))
        return;

    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    
    u16 paletteTag = (species < ARRAY_COUNT(sSpeciesToPaletteTag)) ? sSpeciesToPaletteTag[species] : 0x0000;
    if (paletteTag == 0x0000)
        return;

    const struct SpritePalette* paletteEntry = NULL;

    for (size_t tableIndex = 0; tableIndex < ARRAY_COUNT(sObjectEventSpritePalettesTables); tableIndex++)
    {
        const struct SpritePalette* paletteTable = sObjectEventSpritePalettesTables[tableIndex];

        for (int i = 0; paletteTable[i].data != NULL; i++)
        {
            if (paletteTable[i].tag == paletteTag)
            {
                paletteEntry = &paletteTable[i];
                break;
            }
        }

        if (paletteEntry != NULL)
            break;
    }

    if (paletteEntry == NULL)
        return;

    LoadPalette(paletteEntry->data, 0x100 + (16 * gSprites[spriteId].oam.paletteNum), 0x20);
    ApplyGlobalFieldPaletteTint(gSprites[spriteId].oam.paletteNum);
}